### ISSUE TITLE
CertificateException when trying to fetch keys

### ISSUE THREAD

**Issue by nrpeterson** [open-keychain/open-keychain#2638] opened 2021-01-24 03:37 UTC
I have a private key that lives on a Yubikey.  I've imported it into OpenKeyChain.  Keyserver status is listed as "Unknown", with "Last checked: Never".  I press the 'refresh' button, but it fails.

Also, any attempt to search for keys fails.

## Expected Behavior
I expect it to contact the keyserver and pull the public key.

## Current Behavior
A popup message says "Import Failed".  When I click on "Details", I get the following:
```
[START] Importing key
 [DEBUG] Using keyserver HkpKeyserverAddress{url=hkps://pgp.mit.edu, onion=null}
  [INFO] Retrieving from keyserver: 0x564f9605f1f14816
   [ERROR] Could not retrieve key from keyservers: Network error (CertificateException) for 'hkps://pgp.mit.edu'. Check your Internet connection! 
  [ERROR] Key could not be retrieved! (Network problems?)
 [ERROR] Import operation failed!
```

## Your Environment
* Android Version: 11
* Device Model: OnePlus 8 Pro (IN2025)
* OpenKeychain Version: 5.5
* From Google Play or F-Droid?: Google Play

**Comment by Chrisnetika** [comment] 2021-01-24 20:14
Same here, I thought perhaps it was an app or bc of older android is on my new pixel 4a phone but I just factory reset it and upgraded to latest Android 11 and still the same issue.
![Screenshot_20210124-150916](https://user-images.githubusercontent.com/1711756/105642288-e826fe00-5e56-11eb-8811-f22ea0156627.png)

**Comment by Chrisnetika** [comment] 2021-01-24 20:17
Does it for all keyservers in list btw no matter what order I put them.

**Comment by AdamLeyshon** [comment] 2021-01-28 20:51
hkps://hkps.pool.sks-keyservers.net still works but Ubuntu and OPENPGP are broken

**Comment by nrpeterson** [comment] 2021-01-28 22:41
@AdamLeyshon I actually have the same problem with hkps://hkps.pool.sks-keyservers.net .

**Comment by MaxEtMoritz** [comment] 2021-01-29 10:42
Same Issue for me, Samsung Galaxy A40, Android 10, OpenKeychain downloaded from F-Droid.
SKS Keyserver pool works for me too (thank you for mentioning it @AdamLeyshon), but ubuntu and MIT Keyserver are broken for me (although MIT Keyserver seemed to have general lookup problems at the time of writing the issue).

**Comment by Valodim** [comment] 2021-01-29 12:37
This was an issue due to failed CRL checks in BouncyCastle's TLS provider. I updated the version we use, this should be fixed soon.

**Comment by MartinLoeper** [comment] 2021-02-10 05:54
Hey @Valodim, do you know in which Android app version the fix will be included?

**Comment by Ralffe** [comment] 2021-02-11 12:14
Also at hkps://keys.openpgp.org the key calling does not work.

**Comment by MartinLoeper** [comment] 2021-02-13 11:25
I checked out the current master, built the apk and installed on my smartphone. I can confirm that `hkps://keys.openpgp.org` is working as expected again!

**Comment by Valodim** [comment] 2021-02-14 18:29
fixed in today's release

**Closed by Valodim** 2021-02-14 18:29 UTC

**Comment by nrpeterson** [comment] 2021-02-14 19:03
Confirmed! Thank you.
