### ISSUE TITLE
4.2.3 crash: IllegalStateException: Couldn't read row 0, col 0 from CursorWindow

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#2042] opened 2017-02-07 19:07 UTC
After upgrading to 4.2.3, @Valodim and other users got a crash with the stack trace:
"java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it."

Afterwards all keys were marked as insecure.
This means that the upgrade worked, but consolidate crashed.

We are currently not sure why this happens, but it shouldn't be directly related to the marking of keys as insecure.
For now I deployed a workaround in https://github.com/open-keychain/open-keychain/commit/8fa9f3b2ba084794ca6385450d56378d16efd2b9 and pushed to Google Play with 4.2.4

Ideas:
* https://code.google.com/p/android/issues/detail?id=32472
* https://tapreason.wordpress.com/2014/03/02/how-to-resolve-java-lang-illegalstateexception-couldnt-read-row-0-col-y-from-cursorwindow-make-sure-the-cursor-is-initialized-correctly-before-accessing-data-from-it/
* Looks like there is a maximum of data a cursor can hold around 2MB

**Comment by Valodim** [comment] 2017-04-20 08:56
for the record, I think there is a good chance that this problem was caused by cursor size (it was in my case), in which case it is fixed with #2066

**Closed** 2017-04-20 09:56 UTC
Labels: bug
