### ISSUE TITLE
Installing open-keychain wiped all phone contacts!

### ISSUE THREAD

**Issue by dest4** [open-keychain/open-keychain#989] opened 2014-10-30 17:47 UTC
Hello,
Today, I installed version 3.1 from F-Droid.
I imported my PGP identity, as well as a friend's one.
The whole operation wiped all my contacts, and replaced them with the two PGP contacts of openkeychain.
The software looks really cool, but this is _really_ bad.

OS: Cyanogenmod 11 snapshot M11 (android 4.4.4)
phone: jfltexx (Samsung Galaxy S4)

PS: I had a rather fresh backup, so i'm fine.

**Comment by viric** [comment] 2015-01-21 09:40
I experienced the same. CM 11, android 4.4.4.

I could restore a backup that I luckily had done the day before.

**Comment by viric** [comment] 2015-01-21 09:46
As another detail, when installing openkeychain, I skipped the setup (I didn't want to create or import any keypair).

**Comment by viric** [comment] 2015-01-21 10:26
I tested the very same installation procedure in a Fairphone, Android 4.2.2, and it didn't erase any contact from what I can tell. By same installation I mean same openkeychain version from f-droid and clicking also the skip button on first run.

This phone didn't have contacts imported from old phones (with a "/" in the names, as I mentioned before).

**Comment by Valodim** [comment] 2015-01-21 16:12
I have no idea what could be causing this, and can't think of a way to reproduce this problem, so I'm rather stumped on how to handle this issue :hurtrealbad:

can you perhaps try to reproduce on your fairphone the installation, but with import of the "/" names beforehand? this doesn't seem like a common problem, so it would be tremendously helpful if we knew that this was reproducibly tied to OpenKeychain in any way. we are just chasing ghosts otherwise.

**Comment by viric** [comment] 2015-01-21 16:14
I can try to uninstall it in both Cyanogenmod and Fairphone (in it add slash contacts) and reinstall the same way. Let's see.

**Comment by viric** [comment] 2015-01-21 22:30
I uninstalled it and reinstalled it in the phone where yesterday the contacts were erased, and now they have not been erased. In the Fairphone, then, I haven't even tried.

I can't tell what happened yesterday, that around openkeychain installation I lost the contacts. I also installed Conversation then; I don't know if that played any role. I wrote here just because I found this issue open. I didn't suspect of the software I had installed, but of a Cyanogenmod bug I didn't know about.

**Comment by Valodim** [comment] 2015-01-25 01:33
Hm. That's too bad... there really is just two delete operations related to contacts in OpenKeychain, and both of those seem to be fine. Makes it sort of impossible to debug with the limited information available :hurtrealbad:

**Comment by alanthehat** [comment] 2015-02-05 17:48
Could this be either a feature or a bug in phonebook app?
Have you switched views in phonebook -- all/sim/phone/google?

**Comment by dschuermann** [comment] 2015-03-04 15:02
I just refactored some things on our contact sync.
The only code that _could_ be responsible has been changed:
Line https://github.com/open-keychain/open-keychain/commit/46944198e4a4433025c92eb767118ed5bd4a9e14#diff-dde4119f7068991028febc66a65d4e94L337 did not check for the ACCOUNT_TYPE of OpenKeychain. Still this line should never be executed due to previous checks. However I added an additional ACCOUNT_TYPE where clause.

So closing this for now, please reopen if this is still happening in the upcoming version.

**Comment by Biergartenparadoxon** [comment] 2015-08-16 21:46
Hi same problem here. Installed Conversations, installed OpenKeychain via Conversations, Created a Key for Conversations. Didn't realised, that i skipped the first run dialog, since it started directly with the "Conversations wants to..."(or something like that)-Dialog. and created the key. A hour later, or so, i realised, that i had only 2 Contacts left on the phone, both without a name.

Since i didn't checked the contacts between the instatllations of Conversations and OpenKeychain i can't be sure that it's really the fault of OpenKeychain. I'm just guessing, since in the android-settings it says: OpenKeychain -> last synchronized: 16.08.2015 00:15, which was approximately the time i lost the Contacts.

The phone is linked with a google account but with disabled syncing, so the Contacts were linked to the google account but never left the phone and never actually reached that google account. Maybe this is related.

**Comment by dschuermann** [comment] 2015-11-16 14:14
@Biergartenparadoxon Which version of Android are you using? And which device?

**Comment by Biergartenparadoxon** [comment] 2015-11-16 16:30
Android version 4.3
Kernel 2.6.32_tytung_jellybean_r2
CyanogenMod 10.2-20131110-UNOFFICIAL-leo
Device HTC HD2 (leo)
The rom is on sd-card

**Comment by dschuermann** [comment] 2015-11-23 11:58
I removed one method in https://github.com/open-keychain/open-keychain/commit/af8fd8db695e538de5250af8c9d0f6c19d260a01 that is not needed, but still all resolver.delete select by ACCOUNT_TYPE, so we should never delete other contacts.

**Comment by dschuermann** [comment] 2015-11-23 12:00
We can look into http://stackoverflow.com/questions/7883132/in-android-how-can-i-delete-a-contact-using-my-custom-sync-adapter-only-from-my

**Comment by dschuermann** [comment] 2015-11-23 14:13
I set up an Nexus 5 with Android 6 AOSP vanilla with a google account, added one contact while sync was disabled. Then installed OpenKeychain and enabled link to contacts. The test contact is still present. I will try more exhaustive test methods.

**Comment by Valodim** [comment] 2015-11-23 14:28
nice :+1:

I plan to read up on contact adapters, but the docs are rather longish on the subject. considering there are different merge modes though, it's possible the order of raw contacts added has an influence?

**Comment by dschuermann** [comment] 2015-11-23 14:41
@Valodim Hm yeah the order could have an influence, will test this. I am not sure if the stackoverflow post is valid, though.

@Biergartenparadoxon Are you sure that the Google contacts were really wiped? have you looked into the contact app in the menu under "Contacts to display"? Just want to make sure they are not simply hidden. It would be awesome if you could replicate the behavior on your system.

**Comment by dschuermann** [comment] 2015-11-23 14:51
Just two more finds with limited information:
* http://stackoverflow.com/questions/33134771/android-contacts-apis-why-does-account-syncing-delete-contacts-created-by-my-a
* https://code.google.com/p/android/issues/detail?id=10709

**Comment by dschuermann** [comment] 2015-11-23 15:08
According to docs deleting a raw contact should not delete the aggregated contact: "When a raw contact is deleted, all of its Data rows as well as StatusUpdates, AggregationExceptions, PhoneLookup rows are deleted automatically. When all raw contacts associated with a Contacts row are deleted, the Contacts row itself is also deleted automatically. "

**Comment by Valodim** [comment] 2015-11-23 16:01
The bug surface was reduced with the commit above, I'd be fine with this status on a "better than before" basis. If this really is an android bug, maybe the remaining query doesn't trigger it? Doesn't get all that much better than this, given that we have not yet been able to reproduce this behavior

**Comment by Biergartenparadoxon** [comment] 2015-11-26 14:12
Yes im sure the Contacts where wiped. But i wasn't able to reproduce it. Not even with the old version. But it even behaved a bit different. e.g. the "allow Conversation to..." dialog didn't came up. Are there maybe some Config files or stuff like that left after a uninstall? If yes can you point me to them since i'm not that much in Android development and don't know where they might be. I tried a naive find grep to find them but canceled that bc it took over a day...

**Comment by openbrian** [comment] 2015-12-02 05:10
I was just using Conversations and clicked on OpenGPG.  This prompted me to install OpenKeychain.  I'm using Cyanogen on Nexus 5.  My contacts are intact, even after importing a private key.

**Closed** 2017-04-26 13:22 UTC
