### ISSUE TITLE
Can not enable connect key with contact

### ISSUE THREAD

**Issue by Francoislouis** [open-keychain/open-keychain#2585] opened 2020-09-05 11:54 UTC
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Android Version: 
* Device Model: 
* OpenKeychain Version: 
* From Google Play or F-Droid?:

**Comment by Valodim** [comment] 2020-09-06 19:59
duplicate of #2395

**Closed by Valodim** 2020-09-06 19:59 UTC
