### ISSUE TITLE
Large import breaks on unknown public key type

### ISSUE THREAD

**Issue by rezk576** [open-keychain/open-keychain#1971] opened 2016-12-29 02:54 UTC
When I attempt to import a key using a file picker, I get the message "No keys found". If I try import by the clipboard, I get the message "Bad data". I am quite sure these keys are valid; they are identical files to ones I used to import into APG.  This is an Asus tablet, Android 5.0.2.

**Comment by Valodim** [comment] 2016-12-29 13:38
Is this a public key file? If so, please mail it to me (-> look@my.amazin.horse) and I'll have a look what the problem is.

**Comment by dschuermann** [comment] 2017-02-08 19:58
@Valodim did you receive a key. If so, please re-open, else: We have not enough information.

**Comment by Hawk777** [comment] 2017-02-10 08:40
I don’t about the original reporter, but I certainly e-mailed a few samples to the address shown above in @Valodim’s message.

**Comment by Valodim** [comment] 2017-02-10 09:24
yup, got it. forwarded to @dschuermann, too

**Comment by Valodim** [comment] 2017-02-10 16:09
Had a look: It's an 800kb file of keys, import breaks on an unknown public key type because there is some eddsa key in there. Besides the issue that we don't support eddsa, it's a problem that import breaks when it encounters a malformed key. But this is not a trivial problem: If a key is malformed, we usually don't know where the next key in the stream starts :\

We *do* know in this case, so there are ways to handle the situation better.

**Comment by Valodim** [comment] 2017-09-12 14:07
This should be fixed with #2072

**Closed by Valodim** 2017-09-12 14:07 UTC
