### ISSUE TITLE
Cannot send mail if email address matches more than one key

### ISSUE THREAD

**Issue by nuntius35** [open-keychain/open-keychain#1942] opened 2016-10-30 16:38 UTC
# How to reproduce
1. Create two public keys for the same email address and import them into OpenKeychain
2. Try to send an encrypted email with K9 to this address
3.  OpenKeychain complains that there exists more than one key matching the recipients address and offers a list with checkboxes to select keys
4.  Select one of the recipients keys and press OK
# Expected behaviour
- OpenKeychain uses the selected key to encrypt the message, message is send
# Actual behaviour
- OpenKeychain window vanishes, K9 is briefly displayed, then back to OpenKeychain, the same screen as in step 3 is displayed, both keys are checked. Stuck in a loop, cannot continue to send email.
# Additional information

OpenKeychain 4.1
K9-Mail 5.114

**Comment by zoff99** [comment] 2016-11-06 09:13
i also have this issue.
but even worse, openkeychain selects also keys that are revoked.

**Comment by Valodim** [comment] 2016-11-06 09:41
That seems like a different issue. Please open a new issue with detailed description on how to reproduce (eg including an example key id where you experienced this behavior) .

**Comment by zoff99** [comment] 2016-11-06 09:55
no, for now it's the same issue. because i don't know if the revoked key will actually be used.
it just shows up in the selection. and then it's stuck.

so i need to wait for this bug to be fixed, to be able to say if the revoked key will be used.

**Comment by zoff99** [comment] 2016-11-19 09:21
any news on this? will there be a fix?

**Comment by jp-bennett** [comment] 2016-12-25 15:46
This bug, the broken selection list, also causes problems when sending to an email address that doesn't match any known keys.  Selecting the proper key and hitting OK cycles back to the same selection screen.

**Comment by zoff99** [comment] 2016-12-25 21:13
@Valodim any progress on this?

**Comment by Marwe** [comment] 2016-12-26 20:42
This bug hit me, too. I deleted all but one of the keys to get it working. Would like to see a fix, too. Thanks for all your efforts!

**Comment by tomsedi** [comment] 2016-12-29 10:26
Same here

**Comment by echto** [comment] 2016-12-30 19:30
Crimony.  The day I decide to jump ship from APG to OpenKeychain I have this same issue.  booo.

**Comment by Pacien** [comment] 2017-01-01 09:01
Hi! I am encountering this problem too: I am stuck on this screen.

Other remarks on UI stuff:
- Check-boxes of revoked/expired keys are grayed out and disabled, making them impossible to deselect.
- Moreover, if I understand correctly, the user is expected to select one and only one key. Maybe should the check-boxes be replaced by radio buttons.

**Comment by dschuermann** [comment] 2017-01-10 15:30
Fixed in 4.2. If you encounter other bugs, please open a new issue.

**Closed by dschuermann** 2017-01-10 15:30 UTC
