### ISSUE TITLE
Decrypting from clipboard: text above a blank line is dropped

### ISSUE THREAD

**Issue by jhb** [open-keychain/open-keychain#1598] opened 2015-11-17 16:47 UTC
When decrypting from the clipboard, all text above a blank line is dropped.

Steps to reproduce:

- encrypt the following text to yourself:

> one
> two
> 
> three

- encrypt to clipboard
- decrpt from clipboard
- find only

> three

The number of lines above the blank line doesn't seem to matter.

This also applies when having the encrypted text coming e.g. from an email. The text is the crypttext, AGP or enigmail shows it. 

I am using 3.6.1 (36100), on a german galaxy note 3.

**Comment by Valodim** [comment] 2015-11-17 16:49
Hi, thanks for your report! This seems to be a duplicate of #1592? That bug is fixed on current master, and will be included in the next release :+1:

**Comment by jhb** [comment] 2015-11-17 16:56
Hi Valodim,

I went through the whole tracker, but seemed to have missed #1592. Yes, indeed, I would see it as the same issue. Then I am hoping for a fast release - I use open-keychain on a daily basis (from aquamail). Thanks a lot for the very fast support and the great software!

**Closed** 2015-11-17 17:00 UTC

**Comment by Valodim** [comment] 2015-11-17 17:02
if you like what we do, we sure appreciate them 5 star reviews ;)

**Comment by jhb** [comment] 2015-11-17 17:15
Sure :-). It's 5-starred now.
