### ISSUE TITLE
Linking Github Profile: Failed at Second Step - Post Gist Failed.

### ISSUE THREAD

**Issue by ghost** [open-keychain/open-keychain#2156] opened 2017-09-03 10:50 UTC
## Expected Behavior
Linking PGP Identity in Github should be linked easily.

## Current Behavior
*Post Gist - Status Failed.
*My Github profile has been flagged because of this issue.

## Possible Solution
Check for Github API 

## Context
Trying to 'Linked my Identity' on Github for PGP Fingerprint Verification.

## Your Environment

* Android Version: 6.0.1
* OpenKeychain Version: 4.6
* From Google Play or F-Droid?: Google Play

**Comment by estebanz01** [comment] 2017-09-27 15:25
I found out that OpenKeyChain creates the gist as expected, but it seems that it cannot retrieve it for some reason.

**Comment by estebanz01** [comment] 2017-09-27 16:19
digging into the code, I'm suspecting is dying some place here: https://github.com/open-keychain/open-keychain/blob/dd5d57d06c03670ac96dced469d9c6d3041288c6/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/linked/LinkedIdCreateGithubFragment.java#L295-L310. I think this return is causing troubles: https://github.com/open-keychain/open-keychain/blob/dd5d57d06c03670ac96dced469d9c6d3041288c6/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/linked/LinkedIdCreateGithubFragment.java#L310 but I'm a java noob.

**Comment by yushijinhun** [comment] 2017-09-27 17:25
I think the problem is here:
https://github.com/open-keychain/open-keychain/blob/dd5d57d06c03670ac96dced469d9c6d3041288c6/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/linked/LinkedIdCreateGithubFragment.java#L652-L661

The operations on the OutputStream should be done after connect() is invoked.

**Comment by CHJosephVOE** [comment] 2017-09-28 03:38
📱o)))       any help on linking GitHub to OpenPGP??

**Comment by Valodim** [comment] 2017-10-02 12:41
I suppose something about the API must have changed. I'll look into it when I have some time.

**Comment by rugk** [comment] 2017-10-02 12:58
Also affects Twitter: https://github.com/open-keychain/open-keychain/issues/2175

The "self-verification" directly after creating the Tweet does not work.

**Comment by estebanz01** [comment] 2017-10-02 13:37
@rugk I was able to verify my twitter account without issues.

**Comment by rugk** [comment] 2017-10-02 19:30
Hmm, that's strange…

**Comment by Valodim** [comment] 2017-10-06 17:21
I found a couple of things that could be problematic with linked id creation.

What @yushijinhun says is correct, but should not break the mechanism. Included that change in 65c1ca91d4878e161f933923cd650a59d0490f7c. I also increased the timeout length (c4905c5eda211d13c61bfb5b36d000bdc4b5100f) and fixed base64 encoding during token revocation (fa3345f59544137c1ae1bf2ae8982ea8379a8e4d)

**Comment by rugk** [comment] 2017-10-06 18:39
Only using (F-Droid) APKs for that here.

**Comment by wiktor-k** [comment] 2018-11-06 09:21
@Valodim, please close this issue as Linked Identities are being removed.

**Closed as completed** 2018-11-06 09:28 UTC
