### ISSUE TITLE
Unknown filename

### ISSUE THREAD

**Issue by JasperWeiss** [open-keychain/open-keychain#1687] opened 2016-01-14 20:31 UTC
When trying to open any encrypted data from either clipboard or a file the app gives me an Uknown filename output. When I'm trying to open it it gives me 'show with Nova launcher or decrypt with openkeychain' the latter results in getting to the same screen I came from. 
I'm using Gpg4win to encrypt stuff

**Comment by Valodim** [comment] 2016-01-14 20:34
What app do you use to open from a file?

**Comment by JasperWeiss** [comment] 2016-01-16 07:47
Yes that's what I meant. 
I exported my key to my computer, encrypted some text to my phone's pgp key and then send it through pushbullet. I copy the message and decrypt from clipboard after which it gives me "Unknown filename (touch to open)"
I also tried encrypting the text in a .txt file and send that to my phone but that gives me the same error.

**Comment by Valodim** [comment] 2016-01-16 09:33
Ok, so the problem is that there is no information on the encrypted data whatsoever, it is marked as "binary" and for all openkeychain knows it's just some binary blob. If you encrypt with `gpg --textmode`, it should show up as a text file, which is probably more expected behavior. You can also long-click the file in OpenKeychain to get the context menu where you can Share or Save the file.

**Comment by JasperWeiss** [comment] 2016-01-17 11:51
So it needs to have ASCII armor in order for openkeychain to read it?

**Comment by Valodim** [comment] 2016-01-18 09:12
No, ascii armor is the format of the encrypted data, this is only about the content.

I wonder if we should allow a "display as text" operation even if there is no indication that the contained data is text... while this is *technically* sort of wrong - the encrypting implementation should mark encrypted text as such - this is probably a relatively common use case, using `--textmode` in gpg is not exactly common sense.

**Comment by JasperWeiss** [comment] 2016-01-19 06:42
I don't quite get it to be honest :D An encrypted .txt file (.txt.pgp) should just come out as a .txt right? And doesn't gpg4win automatically mark 'text' encrypted from the clipboard as such?

**Comment by JustinTArthur** [comment] 2016-02-02 04:48
I'm in favor of this "display as text" idea or any simple alternative. So many of the GUI programs people use these days for plain text don't even implement `textmode`.

**Comment by c0re1337** [comment] 2016-02-10 07:54
I have exactly the same problem.  I encrypt a text file on my PC (GnuPG v2) unsing ASCII armor.  The resulting file looks like this:


-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQIMA3tdXfqnDw9GAQ/9HmE9x9pxqcQVFw9eoAYoowyrtDXlo/PfhXz1Wn6QhLei
jsyyybu7Gytj2ACilv9ffxo/TZ9N/z61KWgDpY8iAN/OAor1t4LSockbAuTgnfEk
22TttNd0ppdU2CpfF/RHG6barJHbmhqytn6QkN6MG9imt6BbNig6H+hWn0yWHix8
l1OwSLMvMHUUOGIB+FoAyjc2Fykr4Dx0n6WsWxhS7sgOXCuLNW7YbgGLikJDEgAJ
zr45KR6jgX60H/mfj4K8yjnJ/+lPoLzCwjRJR2CF0hykt6dl32pVr6C6lLxLNnno
1+6okcSzO7HC7kymjlSAe9SCmhS3uXqCvy9iMYNIhpbnPn677YrCgJtFxW7crX74
87RTO4xIzCEOUfRW7nXTGTLBmJua+PLY6yb0lAbUHxbJNcg/2Q1cxDcJ3sERIk1v
04rtaKctx3Y5wbmBAUQ5ia58ATX17jsi0iZwF547nNFc0FbyrrjRizhvrF5yDB3N
RAhQqX4oOAzSljqvvlNtDzHhz7hrFDMweMDzpFxan2TJ+9kK0pUFOmhqkyXrYrCp
MzkhSkojHzNngaZE/UgBrQAHWmrAWmXxH0IuJz4gUhtucaMoOhQ/C2+mr05SuWz0
KmQhbNkmlHpqVUpcdm4umKZmfl4GVCGZXDoTW+Hayeii9+Vpy1C1FoIepnHBqcDS
6QHDAhepAoOW1qw1o0ASfR+L8z9EP3Dlpdqy8ZO+LAG0jB2GeukflWxKq9CrEPHz
ndNg2chVOV7ydRdjhvNefNFVssEdUJIDpXMHWAlcMjiZBk7wyj7FruriwOUYU0XL
vkuV9ydlm6r12Pzhz72fHat89RMDCYojv13EFUU9XfnW3sQ6wmVLRlQ39m3PwFZM
6wNTWuK/H+rWS0VQc3vznu5naJ3kPZa/HpPqfgVbimzeY1J4qBNzLNcZVVBxnbzH
qhhcdfMOaK5P7AKPxmujfQQ4GjvAOu+UKau1/fSzGZKB6IwR6dXCWfI/7qH/tZ3S
WRVBX6RoqXlSC4Rx9DJkLgKH5QgPo6k8x+UziOzlxKO7YLwtZ3EGcdoyCZZyAoa5
jgpNTDsClfBnmXc2lHBxvwE4NDihvVAVpre4SANEiTDMYzpB+EExvmlFwyiQJDmJ
w8H4yVc5Cja5SyqzHFLmRSX964WM8aIxTrErKx7FzOMKGgz1TeBdCz/ma4anh5LW
Xw66ILgR1cg8uv9AKDJGXgEeVvJX9mtAEM53r+qrpPpP9UCjZtPlIzPWYuRe7AMQ
eQWBlexWUNvi68Bjrs4Itz+x7Am6U0LBekoN7DInJfChjIqviwxUERECFS7D//ys
VEXHhzGu+LhLZU4FI1yNUMAlxMgQslEykzwIyMeCS1PMUYipeSswg7YpAcpG11oJ
nLdvZVFKl8cKO9FcD8Ob3tB7fuF19DF/iUoiNNR6urwlMs/SYJV6W7uJuuIO7kzu
qSDanUlpstwiGaohrOGSDMovjQ==
=63mU
-----END PGP MESSAGE-----

This is NOT READABLE by Openkeychain as a file even though it's saved as a plain text file.
It's also not decryptable if copy / pasting the contents to Openkeychain.

What puzzles me a bit is that i'm 100% sure that it used to work or works "some times"

I tried downgrade to next last version of Openkeychain: no difference.

I tried to downgrade to a few versions back: no difference.

I tried to downgrade to a REALLY old version (like one year ago): lot's of other trouble and can't read the encrypted file.

I'm using an Xperia X3 phone with the latest Android + latest system upgrades.
I'm using Kali Linux 64 bit and GnuPG v 2.

gpg (GnuPG) 2.1.10
libgcrypt 1.6.4

I first noticed the issue when trying to open some files in my Dropbox that's encrypted with GnuPG



Best regards   c0re

**Comment by Valodim** [comment] 2016-02-10 11:34
We know how to handle this at this point, thank you for your reports.

**Comment by c0re1337** [comment] 2016-02-10 14:28
Thanks for the feedback!   I'm looking forward to be able to test this client in my "workflow". 

/ c0re 

On 10 February 2016 12:34:47 CET, Vincent <notifications@github.com> wrote:
>We know how to handle this at this point, thank you for your reports.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/open-keychain/open-keychain/issues/1687#issuecomment-182325978

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Closed** 2016-02-23 15:01 UTC
Labels: in progress

**Comment by gator2000** [comment] 2017-04-29 13:03
Hi there,
I'm using the latest OpenKeychain version (as of Apr 29, 2017) and I'm running into this same issue, or a variation of it.
The issue is not only with text files, but with any file encrypted on Windows using gpg4win.
From the comments above, it sounds like the fix was to try to guess when a  file is text or not. But could the actual problem be related to how OpenKeychain is handling the output file name?
From what I see, OpenKeychain decrypts the file just fine, but then it displays the message "Unknown filename (touch to open)".
But when I touch to open, it looks as if OpenKeychain is called again by Android, as I get a "Decrypt with OpenKeychain" popup. When I touch that popup, I get and error saying "Encountered an error reading input data".
Could it be that instead of trying to open the file using its original name, OpenKeychain is passing the name suffixed with ".pgp" and that causes a kind of "loop"?
Thanks
G

**Comment by dschuermann** [comment] 2017-04-29 13:25
@gator2000 Please create a new issue.

**Comment by gator2000** [comment] 2017-04-29 13:31
Sure, will do. Thx

**Comment by gangeleski** [comment] 2018-01-03 08:59
Same issue! When I open encrypted file from Gpg4win I get "Unknown filename (touch to open)". Using the latest version of Openkeychain 4.8.1
