### ISSUE TITLE
Encrypt/Decrypt text doesn't preserve new lines

### ISSUE THREAD

**Issue by dmaroulidis** [open-keychain/open-keychain#1985] opened 2017-01-09 13:41 UTC
When you encrypt some text in OpenKeychain and you use the newline character, it's not preserved during decryption.

**Comment by Valodim** [comment] 2017-01-09 13:43
The error description is very general, and in a quick test I can't reproduce it. Can you give a specific scenario and steps of what you're doing (including the text you type) for this to occur?

**Comment by dschuermann** [comment] 2017-01-30 16:37
@dmaroulidis We need more information, thus closing.

**Closed** 2017-01-30 16:37 UTC
