### ISSUE TITLE
PendingIntent (for unlocking key / enter password) returned be decrypt operation becomes stale on next decrypt operation.

### ISSUE THREAD

**Issue by mgeier63** [open-keychain/open-keychain#1697] opened 2016-01-20 11:48 UTC
Consider this use case:

An app calls decrypt and gets back a PendingIntent to enter the key password in OpenKeyChain. The app then shows a notification that tells the user that he needs to enter the password in OpenKeyChain, when tapping that notification the original PendignIntent from OpenKeyChain will get fired.

If the app now does another decrypt information (in the background), before it uses the original PendingIntent to unlock the key, it gets a new PendingIntent and the PendingIntent from the first operation becomes stale, i.e. can't be used any more, will throw an IntentSender exception or so when attempting to use. (Note that possibly this might also happen if another app does a decrypt operation requiring the same key, but I haven't checked this scenario yet) 

I had to do implement quite some workaround in my app to make sure that only the latest PendingIntent gets used and/or that no other decrypt operation happens before using the PendingIntent of the last operation.

A possibly simply solution for this would be if you would just somehow expose (possibly in the OpenKeyChain Intent API) a method or intent that one could call _anytime_ to unlock a specific key - even _preemptively_ before attempting a decrypt operation.

**Comment by Valodim** [comment] 2016-01-20 17:19
The api by design requires a client to be able to handle pendingintents as a result at any time. Trying to avoid that api contract by preemptively caching a passphrase is a huge hack.

from the top of my head, I'm not sure if it's really necessary that pendingintents are flagged with `FLAG_CANCEL_CURRENT`. if we are lucky, just removing that might fix your problem?

**Comment by dschuermann** [comment] 2016-01-20 17:51
Yeah I think we could remove ``FLAG_CANCEL_CURRENT``. But that needs to be tested, I remember some problems having PendingIntents recycling old PendingIntents.

Keep in mind that unlocking a key is only one possible user interaction requiring an Intent. Other interaction is required if you use YubiKeys for example or if no keys have been found for a user id which was chosen. Even more, it can happen that you get another PendingIntent after processing the last PendingIntent to unlock the key. So exposing a specific Intent for unlocking the key would not help. Your app needs to keep a state in form of the returned Intent data in onActivityResult that needs to be passed again and again until the operation succeeds.

**Comment by dschuermann** [comment] 2016-01-20 17:52
@mgeier63 Can you make the change, test it, and make a pull request?

**Comment by mgeier63** [comment] 2016-01-21 04:41
Simply removing the `FLAG_CANCEL_CURRENT` flag will not suffice methinks. From the PendingIntent android docs:
```
 * <p>Because of this behavior, it is important to know when two Intents
 * are considered to be the same for purposes of retrieving a PendingIntent.
 * A common mistake people make is to create multiple PendingIntent objects
 * with Intents that only vary in their "extra" contents, expecting to get
 * a different PendingIntent each time.  This does <em>not</em> happen.  The
 * parts of the Intent that are used for matching are the same ones defined
 * by {@link Intent#filterEquals(Intent) Intent.filterEquals}.  If you use two
 * Intent objects that are equivalent as per
 * {@link Intent#filterEquals(Intent) Intent.filterEquals}, then you will get
 * the same PendingIntent for both of them.
```
to resolve this you would also have to return a distinct `requestCode`  for every distinct PendingIntent - currently the `requestCode` is hardcoded to 0.

One naive way to tackle this would be to just have an integer variable increment every time you crate a PendingIntent. While this would probably work from the client perspective, it might eat up resources on the OpenKeyChain side of things as those PendingIntents would stay around forever and this could sum up over time. [also this would probably require to somehow add the process id of the caller to the actual requestCode on the server side, to make sure that two separate clients specifying the same requestCode would still get two different PendingIntents]

If we add `FLAG_ONE_SHOT` then at least the intents that actually get used by a client would automatically be cancelled after use. But because you can't be sure that the client will actually use the PendingIntent at all times the resource use problem would remain.

Of course the server could somehow do some garbage collecting, based on a maximal number of PendingIntents or maximum age of the PendingIntent, but somehow I feel this approach would look a bit hackish and would probably be an overkill - not to mention the additional complexities of automated testing when having a time based expiry.

**Comment by Valodim** [comment] 2016-01-27 10:39
none of these solutions sounds very good to me. :(

Is serialising these operations really not feasible for your app? keep in mind it's no problem to retrieve a new pending intent at a later point, and you need to interrupt for user interaction anyways. Given your notification use case, storing and executing the PI might not really be what you want, but rather a restart of the whole operation - the password might have been cached in the meantime, for example.

**Comment by mgeier63** [comment] 2016-01-27 14:16
Don't worry about my app, I have workarounds already -  I'm repeating the full operation now and am also serializing access to some of the API functions.
I was just raising this issue as a potential improvement for the OpenKeychain API in case other people start using it in a multithreaded way and run into the same issue..
But due to the lack of a good general solution, maybe a warning or hint in the javadocs and/or wiki is the best way to address it for now.

**Comment by dschuermann** [comment] 2016-02-07 20:44
We will keep the current behavior, thanks for your input @mgeier63 
Will closing this as "wontfix" for now.

**Closed by dschuermann** 2016-02-07 20:44 UTC
