### ISSUE TITLE
Importing two different keys with same email address. Name conflict

### ISSUE THREAD

**Issue by Morthawt** [open-keychain/open-keychain#2308] opened 2018-04-22 14:22 UTC
The name of the new key has the name of the old key which uses the same email address.

## Expected Behavior
I should see the public key of my original key at the bottom and then the new full key which uses the same email address should appear at the top with it's actual name.

## Current Behavior
Install public key using my email address. Then make a new key on the computer with a different name (in this case I had added (Mobile Phone) to the end, so the first part of the name is the same as the other key. Then when I check in the "My Keys" list, my new key has the name of the same as the separate key which I have only the public key installed.

## Possible Solution
The check for the name of the key should be checked rather than making an assumption based on the email address and existing name for it.

## Steps to Reproduce (for bugs)
Already described.

## Context
I am messing around making a new key and I simply added an indicator to the name so that I know that both keys are real and mine but one is weaker for phone (Yubikey Neo) usage.

## Your Environment
* Android Version: No clue off hand, unimportant for this issue.
* Device Model: Samsung S5 Mini
* OpenKeychain Version: Latest
* From Google Play

**Comment by dschuermann** [comment] 2018-04-22 17:05
Hey, can you include a screenshot? I am not fully sure what issue you mean.

**Comment by Morthawt** [comment] 2018-04-22 17:29
A screenshot? It has the exact same information as I typed out and nothing else?? https://i.imgur.com/F1se3oY.png

**Comment by Valodim** [comment] 2018-04-22 17:33
I also didn't understand the issue from your description, sorry.

That looks like a screenshot to a different issue though? :)

**Comment by Morthawt** [comment] 2018-04-22 17:34
Ah that ticket. The screenshot would have my personal information on it. But actually I think I may have figured it out. When I open the main full key it has Mobile Phone under the name, but there's no ( ) either side. So I think the app is removing the brackets and only wrapping the text on a new line which there is no new line in the main list of keys perhaps? It has as it's real name:

**The Name On My Key (Mobile Phone)**

But it only shows:

**The Name On My Key**
**Mobile Phone**

But only after I have clicked it to see all the details.

**Comment by Morthawt** [comment] 2018-04-22 17:36
So the long and short of it is, two keys installed. One public and one is a new key with private key. Both are for the same email address and the names are the same except one has (Mobile Phone) added to the end of the name. Both show the name before the (Mobile Phone) part, so the only way I know one from the other is that one is a public key and one has a private key so they are in separate sections, otherwise I would have no clue which one I want to encrypt something to unless I go through each one and inspect the identities on each key to read the full non-truncated name.

**Comment by Morthawt** [comment] 2018-04-22 17:37
So what I expect to see is:

> **The Name On My Key (Mobile Phone)**
> 
> **The Name On My Key**

But instead I am seeing:

> **The Name On My Key**
> 
> **The Name On My Key**

**Comment by Valodim** [comment] 2018-04-22 17:45
the ( ) part is interpreted as a "comment" field, and displayed as such. comments are [considered a misfeature](https://debian-administration.org/users/dkg/weblog/97), which is why we only show them in a secondary position in the details of a key. in the main key list, they would make the items much more visually noisy.

for the purpose of distinguishing keys that have the same name and email address, there *should* be a creation date displayed on both of those keys. this works well for the typical scenario of similar keys, where there is an older and a newer one.

**Comment by Morthawt** [comment] 2018-04-22 18:13
Yeah. It just feels a bit clunky and not accurate.

**Comment by Valodim** [comment] 2018-04-22 19:02
Use of comments is not a workflow we encourage, which is why we don't optimize our UI for it - see the link above for reasoning about that. Your use case sounds reasonable at a first glance, however it only works if users manually select keys among multiple for the same email address for different purposes.

My suggestion for a nice workflow would be to use different e-mail addresses to distinguish those keys, e.g. `morthawt@example.org` and `morthawt+mobile@example.org`. That way, there is a clearer distinction that works with existing recipient choice UI and doesn't rely on openpgp's comment field, which is unusual and often misunderstood. This type of "tags" in email addresses is also widely supported in e-mail MTA software (e.g. postfix) and providers (e.g. gmail).

I'm closing this issue as this works as intended. If I misunderstood you about the creation dates and they aren't actually displayed for you, that'd be a bug, please reopen the issue if that's the case.

**Closed by Valodim** 2018-04-22 19:02 UTC

**Comment by Morthawt** [comment] 2018-04-22 19:04
I never use the comment system. I only ever set the name on my keys?

**Comment by Valodim** [comment] 2018-04-22 22:03
A user id in openphp consists of name, address, and a comment in parantheses. That is what you have been using, unless I completely misunderstood, and is also what the blog post linked above advocates against
