### ISSUE TITLE
Crash on Confirming Match of Yubikey to Downloaded Key from Server

### ISSUE THREAD

**Issue by mezinster** [open-keychain/open-keychain#1359] opened 2015-06-23 14:24 UTC
I am trying to BIND my YubiKey to the Key in Openkeychain.
App Crashes while holding a key near NFC-enabled phone and the same time pressing the "BIND KEY" button.

Google Nexus 4
Cyanogenmod 10.2.1-mako
Android 4.3.1
Openkeychain 3.2.3 from F-Droid

**Comment by mezinster** [comment] 2015-06-23 14:25
By the way, that was not the issue in the Android Market Version of the App.

**Comment by Valodim** [comment] 2015-06-23 16:08
am I correct in assuming your yubikey carries only specific subkeys of your public key? if so, this is a duplicate of the already fixed but not yet released #1315

(we should really get a release out)

**Comment by mezinster** [comment] 2015-06-23 16:23
@Valodim looks similar.. My card consists of 1 record (RSA, 4k master, 2k signing, 2k encryption, 2k auth)) and the URL pointing to my public key...

So my steps to reproduce that were : on a clean installation of OKC import a key over NFC from my Yubi (actually that was a downloading of a key thing [as i understand, the URL only were taken from yubi that moment]) and after that i was able to press BIND KEY and see crash...

Let's wait for an update.

**Comment by Valodim** [comment] 2015-06-23 16:24
if you have an android toolchain set up, you could also test on current master. but yeah, if you have a 4k master key it's definitely the same issue.

**Comment by mezinster** [comment] 2015-06-23 16:28
@Valodim I've sent you an email with my gpg2 --card-edit output. Please check and correct me if i am wrong...

**Comment by dschuermann** [comment] 2015-06-30 12:24
Please try again with version 3.3 that has just been released (will appear in some hours on Google Play and F-Droid). If this issue is still present, re-open this issue report.

**Closed by dschuermann** 2015-06-30 12:24 UTC
