### ISSUE TITLE
Long (4096 bits) size key doesn't seem to be supported

### ISSUE THREAD

**Issue by zonArt** [open-keychain/open-keychain#2501] opened 2019-10-25 09:30 UTC
I'm using OpenKeyChain in conjunction with password-store like many people I guess and am facing an annoying issue. The password cannot be decrypted because it looks like the key is too long

## Expected Behavior
Encrypted data should be decrypted without issue

## Current Behavior
Failing with this error message:
`Error: transceive length exceeds supported maximum`

## Steps to Reproduce (for bugs)
1. Encrypt data with your 4096 bits public key (this step doesn't seem to be problematic)
2. Try to decrypt it (doesn't work for me)

## Context
Trying to use password-store to manage my passwords with the help of OKC and a YubiKey 5 NFC

## Your Environment
* Android Version: 6.0.1
* Device Model: Nexus 5
* OpenKeychain Version: 5.4
* From Google Play or F-Droid?: Google Play

**Comment by zonArt** [comment] 2019-10-31 19:03
Am I alone in this case? Do you guys use smaller keys? Or does it maybe work with more recent version of Android?

**Comment by alci63** [comment] 2019-11-27 09:36
Hi @zonArt . I encounter the same problem, but I'm not sure it is related to key length. I think it has to do with the way your NFC controller works in your Android phone.
But this is still unclear to me... any educated comment would be nice.

**Comment by Valodim** [comment] 2019-11-27 10:26
Phew. We did test this on some phones and it worked, so my guess would be that this is indeed caused by an NFC controller that incorrectly supports the maximum length of transferred data units.

I guess we could restrict ourselves to a known minimum limit, or add exceptions for known bad models.

**Comment by alci63** [comment] 2019-11-27 14:15
@Valodim I think android default to 261 bytes as the maximum length, and offers OEM a parameter to change it (ISO_DEP_MAX_TRANSCEIVE).
I've been trying to tune it on a Samsumg Galaxy S9+ with a Lineageos based OS, but did not succeed until now (see https://gitlab.e.foundation/e/os/android_frameworks_base/issues/19)...

Indeed, dealing with the 261 bytes minimum value would be great, as it is a bit frustrating not to be able to use the Yubikey on that phone...

**Comment by zonArt** [comment] 2019-11-27 20:42
Thanks for these explanations, looks very interesting

**Closed** 2019-12-05 09:48 UTC

**Comment by zonArt** [comment] 2019-12-05 14:27
I think I have no other choice than generating new keys which are "only" 2048 bits long. Thanks dudes for the provided bit of information, totally makes sense

**Comment by alci63** [comment] 2019-12-12 19:37
@Valodim I finally got open keychain + yubikey 5 NFC working on my Galaxy S9+ running /e/ os (lineage based).
It was definitely due to a problem in the NFC stack where the ISO_DEP_MAX_TRANSCEIVE_LENGTH parameter was not set in /vendor/etc/libnfc-brcm.conf file.
Setting it to 0xFEFF solved my issue.

**Comment by nh2** [comment] 2020-12-12 21:53
I get this problem also on my Moto X but with a rsa2048 encryption subkey on the Yubikey 5 NFC.

As ween from #2049 (that @Valodim helped me with), it works with the Yubikey Neo.

**Comment by nh2** [comment] 2020-12-12 21:56
Related: https://github.com/NXPNFCLinux/linux_libnfc-nci/issues/116
