### ISSUE TITLE
Cannot connect to Twitter/GitHub for verification

### ISSUE THREAD

**Issue by rugk** [open-keychain/open-keychain#2175] opened 2017-09-29 19:50 UTC
## Expected Behavior

Verification/Sending should work.

## Current Behavior

Any network connection to Twitter (when verifying tweet) or GitHub (when trying to publish gist, after login) fails.

## Steps to Reproduce (for bugs)

1. Go to one of your keys.
2. Try to publish it on Twitter or GitHub.

## Context

Note that I verified that network connections in general work. The flattr button can be loaded and keys can be renewed.

Possibly this is this infamous [Android 7 bug](https://stackoverflow.com/questions/39133437/sslhandshakeexception-handshake-failed-on-android-n-7-0)? Although I am on Android 7.1.2, so it should be fixed there, AFAIK.

## Your Environment

* Android Version: LineageOS 14/Android 7.1.2
* OpenKeychain Version: 4.7
* From Google Play or F-Droid?: F-Droid

**Comment by Valodim** [comment] 2017-09-30 19:23
I'm not sure what part isn't working here. Is it verifying someone else's linked ids? Or creating your own?

**Comment by rugk** [comment] 2017-10-01 08:53
Creating my own. It is always the (first) step, which needs internet connection (e.g. for Twitter, it uses a third-party Twitter app or website to post the tweet, so this works, but the in-app self-verification afterwards fails; for GitHub I cannot upload the gist). It always tells me it can't connect or so…

**Comment by rugk** [comment] 2017-10-02 12:37
Ah wait, for GitHub it actually could upload the gist. I also see "OpenKeychain" in my [session list on GitHub](https://github.com/settings/security). So it could connect, but for some reason in the app it still claimed it cannot upload the gist.

**Comment by Valodim** [comment] 2017-10-02 12:40
Since this is about creation and not verification, this is a duplicate of #2156

**Closed by Valodim** 2017-10-02 12:40 UTC
