### ISSUE TITLE
Automatic upload is an incredibly bad choice

### ISSUE THREAD

**Issue by jbash** [open-keychain/open-keychain#1887] opened 2016-06-10 01:26 UTC
So, I downloaded the app, just to play with it. And I generated a key (using a smart card).

And, unlike any other PGP implementation I've ever seen, it instantly and automatically uploaded that key to the keyservers. It took this irrevocable action with no direction from me, no warning, no confirmation, and no chance to prevent it. The only way I even know it happened is because of a message that flashes on the screen for maybe one second.

If I'd needed privacy about the fact that I had a key, I would have been hosed. And now the database is polluted with yet another useless, confusing revoked key that can never be removed.

I was shocked. I must have generated dozens of PGP keys for all kinds of uses over the last 22 years. Of those, there have been maybe 4 or 5 that I actually wanted to publish.

Seriously not a feature. Please at least ask the user to confirm these uploads.

**Comment by dschuermann** [comment] 2016-06-10 06:40
duplicate of https://github.com/open-keychain/open-keychain/issues/1847

**Closed by dschuermann** 2016-06-10 06:40 UTC

**Comment by Valodim** [comment] 2016-06-10 13:38
actually, the "synchronize with the Internet" checkbox is the one single checkbox we have in our entire key generation process, and it is one out of four total user inputs (besides  name, email, passphrase).

it's interesting that you missed this, I wonder if we should give this its own dialog. then again, if you created dozens of keys, I suspect your expectations are very biased by your usually used implementation, so it's not impossible we are doing everything right in regard to most users, but simply clashed with your particular expectations here. I'll give this some more thought, maybe a checkbox is not the right widget to go with here.

**Comment by jbash** [comment] 2016-06-10 14:00
I also missed the existing GitHub issue, so apparently I was having a blind evening. I *did* search for "upload". Sorry about that.

You're right that my expectations probably colored my interaction with the app. I don't think the checkbox is enough for anybody, though. If you *do* use a checkbox, I think that it should be off by default, because that's safest... but I also understand that that means new users may have no idea that they need to publish their keys.

If it were me, I'd have a separate screen with something like "Upload your public key to the Internet for others to find?", big fat "Yes" and "No" buttons, and no default.

**Comment by Valodim** [comment] 2016-06-10 15:17
I would argue that, in the current user culture of pgp, publishing one's key is the default option, *not* publishing it is a special choice. I don't have a lot of time right now so I didn't think all of this through, just writing down some thoughts from the top of my head::
* Deciding not to publish a key is a thing which makes only sense for people who have more than one key. That is already a special scenario.
* Anyone can publish a key, so in order for a key to stay not published, even a single correspondent who signs and uploads it already breaks this
* There is no established mechanism to share keys besides key servers, other than to manually share files or at most "attach key to email" and "click to import", which is way too inconvenient. By comparison, "can't verify signature, check if we can grab the key from the keyservers" works and is established
* Keeping a *public key* secret makes no sense. The thing you *actually* want to keep secret is the key's association to you, i.e. your email address. If that is the case, it seems like the wrong approach to attach a user id with this information to it?

**Comment by jbash** [comment] 2016-06-10 17:15
I agree that it's pretty uncommon to want to keep a key *secret*.

But I doubt it's uncommon to create a test key, especially if you're a new user of something. Given how tricky crypto is, it's probably a *good idea* to have run through the procedure before you do it "for real".

Personally I tend to create special-use keys that are never shared with anybody but me. Unusual, but you still don't want those keys cluttering up the servers.

**Comment by Valodim** [comment] 2016-06-10 19:26
keyservers cannot be "cluttered up" - they are unfit for any other purpose than key lookup by fingerprint or (maybe) long key id
