### ISSUE TITLE
is there a way to query keys from Symantec Unified PGP Server

### ISSUE THREAD

**Issue by anindyar** [open-keychain/open-keychain#1761] opened 2016-03-06 23:27 UTC
Hi,

I just wanted to know is there a way to query keys from Symantec Unified PGP Server over LDAP/S ?

P.S . sorry if I am putting the query in wrong place / section.
 
Cheers,
Roy

**Comment by dschuermann** [comment] 2016-03-06 23:28
No, duplicate of https://github.com/open-keychain/open-keychain/issues/1195

**Closed by dschuermann** 2016-03-06 23:28 UTC
