### ISSUE TITLE
Kleopatra can't decrypt non-ascii armored file?

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1178] opened 2015-03-23 16:06 UTC
from ml:
> but I find the encrypted file can't be decrypted by 
> Kleopatra/gpg4win (the armored version of the same files do work fine).
> But that shouldn't be a problem for my applications since I'll be using the 
> BC provider directly on the server-side -- I think it's a bug (or just lack 
> of binary file support) with the Kleopatra program. 

Needs testing.

**Comment by AndreHeinecke** [comment] 2015-10-23 09:26
Kleopatra / Gpg4win can work with non-armored files. It's the default Kleopatra produces.
Vincent sent me a test file and I was able to decrypt it using Kleopatras Decrypt / Verify File option.

Are you using different file extensions for armored / binary data? Like .asc / .gpg? In that case the user might have a binding configured for .asc and not for .pgp.

**Comment by Valodim** [comment] 2015-10-23 11:56
Our default file extension for non-armored files is .pgp

cannot reproduce -> closing ticket for now

**Closed by Valodim** 2015-10-23 11:56 UTC
Labels: help-wanted
