### ISSUE TITLE
Cannot find/see files with unicode-filename

### ISSUE THREAD

**Issue by tran-nathan** [open-keychain/open-keychain#1346] opened 2015-06-14 09:26 UTC
If the filename has unicode characters then OpenKeychain won't see them. 
For example, I save an encrypted file "Tài Liệu Đọc Trước.doc.pgp" to download folder. If I try to decrypt this file with OpenKeyChain, it won't see this file in download folder at all. What I have to do is change the filename to non-Unicode, something like "Tai Lieu Doc Truoc.doc.pgp" (no accent marks), then OpenKeyChain can see this file.
Nathan Tran

**Comment by Valodim** [comment] 2015-10-25 19:16
cannot reproduce with latest version, I created a file with your exact filename and it showed up in the file listing, and I was able to encrypt, decrypt, and share the file, with the filename showing up correctly all along the way.

closing for now, please reopen if the issue persists

**Closed by Valodim** 2015-10-25 19:16 UTC
