### ISSUE TITLE
Error! Could not decrypt this message: Error: Ascii armor integrity check on message failed: '' should be 'VQBO'

### ISSUE THREAD

**Issue by sharpe5** [open-keychain/open-keychain#1986] opened 2017-01-09 15:13 UTC
I encrypted a message with OpenKeyChain v4.1 (41010) using K9 on Android. This message failed to decrypt on my PC with the following 3rd party PGP apps:
- Mailvelope (Chrome version)
- Mailvelope (FireFox version)
- CryptUP (Chrome version)

In every case, the error message was the same:

> Ascii armor integrity check on message failed: '' should be 'VQBO'

It worked fine when decrypting on Android/K9.

Here is the message (its the same for Mailvelope as well):

```
Message is either badly formatted or not compatible with CryptUP. 

Ascii armor integrity check on message failed: '' should be 'VQBO'

-----BEGIN PGP MESSAGE-----

hQIMA6J6dUviQC7vAQ//SQjiQvVYhpat+8K65AJbUjgVGXBXhDLzQNqP69U0uKkp
RWBNhu4J/RUCDdMarDu9CSYZiAEeYAZILHEhpxaSLIHW+VccyS7Ov4CBLpcHE9lW
8oKnhs6CH0Fgi6sz1qH8X+DaWR9DXlnpfvTJ/OmmbV2f4MBLXdiWKnrw+GD9Sv06
013291cVT+Ra5SWwhLXO7S+19G3eYUQy7qgDXqGOO9G39BjCnjpQsnKEpR8yJtEE
FiDo2mSJyGmoPqMpKeeLfHs5zRMh9326WwgJSLiCn2EVMU7z05XMB9jyBDAZ26Zx
+k0MNZ8UjuyaysvfBbWjiMAUGxEKno+pMCgoteykDaf0hlTIWgJrVJDao2D/RdAc
glsCSeNDUEdG9vkI0Knx1jecft9qPfdmDTHvMm1vaDowEQa7MXA8ktl+cVdaKsSG
OZZmmFxlIlMb58dX4VDreebv/AcxtSh2yfKPSO3z2VU9oGSl1W4Jey+VUcTLxH2y
QEPP/R5LgmfmnBzj+Rl3408rC6ukKMhI4Xv7OgIx9vDGE+xRs+lrYSnE0ATSBTQ0
CguhcYJDeWoze44au68MwJ+KJGysvNUWuXfk6jhfNFN72scb6nqEWBET02/y/SsY
GMfJM3PN94vQ7BQoKSPNtQ60HU01Zj1ngaUz9erQjooFMW5JlwiKU54JzabcgRuF
AgwDiOGbcUTEMM0BEACQUnNoK37GC4VaVWbnbmzqM6XUDabomP1Go6e1TI9PI8H8
YNXhF6JIeclTeEZwViu/9ngAonkDVe/FtyTzwRjBbiQ7+hJOee7oN1RpfXeowVGV
BLPJ+DqF3z5lg5IujejflXYNQGbej2Wx061qLp7etbirmJLqFNf0SwKENf0sEvTs
NJRHRk5seCYstEuI+QMnt6bIfTlkDZQdKzwzHVgNUUr7XugJFMxnVqpBu6y/4cyo
ruGSTSU5W5IqAUy3YHvy/zFpqRfB5MpFqhR7YCqIcdyNJ7vTyIjIkqTAzhuChe7R
Mm0ywmNFanZB3V5/R0rcSRqNt5icctWTN+MRPH1UaRfMzF0sbS0gejCSzgqulUTb
Ql/vh+FStW1vKuxoc35oP4Wt8IsES0QMSAynbQhrqXdJk3qAEvrKKDzsfJGuBmrr
thvweTwU0jGYnzfiTu3rFaEX9UlgfA0pENMGzQB4EgvoDk3cGMPwDy3HJ6yUsmFv
aRbkOl+6HAyqcwf4drNcJi5pWYH935aDoF61vLWUdeIuR5n+ORAlcGsF97qZL3tV
JTkoPZVDR/hLI3QylpRBQYcwXr48GqM+jIoiFKYJOXiMsTrwWTpbyOv9CuEZZDPN
DW5KitU1g6nxayyULThR4rF9rRqcM91YjYRPWK3cV7zkwm82Xbw5YYk0DN1Iw4UB
jANhKyOXt2PxSAEMAKpLULcKw0MkDlAgPXQEsDiqfi/HlAVV2nJ4f69WQYC+p2ET
agH8+7o/2mGo7QOYzL43O8WzHQXjnYDX+xp1vz46ggkXmOU6xaTUXWv//MOM+h72
ICqTEl04dWQ+p8aKtRzTM0zOjgMP3UoC1cpU/UeHj1qaFw3waz0XOhtIwE/r5K6Y
tlizsUIYggFydKr7zKYV1aZlwPgNJqfpgahVAKFvNtlRaMIg16XNbyoOC3MlmKdc
En3NTnWmlWvUeZUO3yw8Q9GbNgtOB0YeY6BFso0D86y0vdjIHZYsO16sTtV3VAx7
/jr/lFFSVJqPJz67uzSavSd4PktJwyyvpmiQtnDLq3znkkTO3tdejuWw7LkY+Zx8
CPfTTFlZXUGmtP/QwRWklKjPkmc0JtaGC5aiygmMwE5TkmRn7kHjj5+0u6nKK+0B
x3IPqOgvuCDnlrTSkNCcn9V2PXxeH60Ttrgo6TggF3Yku3cYnAOUC9DOvZF5duyK
0G9yt9uw8UE6GJGbf4UBjANhKyOXt2PxSAEMAJ+CzK3gKARvD6ql9OzYnojqxoui
Hcrb9rrmERdiwlgs96QE+U4idBIS1q8z3pO1Wg8ZdKP7I7v+RnClGi3OsIwlzsz2
sIzNyw0+YURKhN2H1IWn1BJvMI4U3+CmesiMqqGUQpkeohcxZev9X0iJ1PPY2liP
WNMeTh00ZQoyDhMRGj3YHSkvPvoIxpKwoqSiL5Se5DVCr4MwHBvQwGWurQe8CIuI
s1TZjKFxaNWUpi6oYwKXfV9rlX9KgVF36RUhtaeEGiQJ9FoBbQww0sF2lgbZVdFK
1SYSXJ3QVfo/f1rpQ0XHk1a3upFF3tn7fVDKD56gtqQwm5iB1yJZIrmoB/mCEwMK
2/y2i9EPN/bZ3TTi1TDm5qFpSpsN1pcg60HZUh1ftweur10dEe+YBhiDTu/ilGvR
k4s/9tcgYZ5IKBbcX82dTylvy4E+qRYfvqEus9acwtX5rxoCRxs0MRVvaMKxQQPs
ws6i4GnPS+497NKHeMfmDfIE0uSj4IuAwjjg/tLBbAG4ph/4n9CzOi4lZMG2BJdF
c8zMXayuqh7miQs5PNuKht1J6ZhYCkOcDdnmEBX31kf1g4w58RsZ3dAhANfMWNDM
QF2WBBnqA1wh6mDnCGqCaoTbNMKsFVKmx/KdGZ7iah/9YWqXylf95K2/X/aHceU8
DEdOlwDoVjXqJ+8oXr//NvqDhr1kk2qEdMobA9awuP6imjtJVxQLa6aecfINph4p
1yzfSfqUJcLvJqSk+fHWPJJIP2/4V38xErcVZ31SdiFIjBKYottLqfaDPBh1Uppz
3r09YfBse903x9uoBXi0zB34NTkSnX2XmrA+Ukzg6TPyo1FuoKSo8o9HGQ69ho0w
7SYr8UjQtRYkKyKO7xeZ5tMnxfGWeTMfqX1eTQeJ16OboBhpphXZEuspbme02NJt
5F9tL/ALHydowNFuDqct1Z89mxQg4KmB1BzapdEXhrbYSNeh9yPdrvykPPdBuL3t
R4ns91/hTyx5gEvSNbmN5ff/BaZE4SFay3NtCoPvU/QBjOQ/s1S0HkPTBtz0051O
cSh4K+1GXOfsIAN9Af5oszlzdu7v2yEut5DgRtupddzaoqbRVM+3jSmhFqatwVJI
ZffbIKU5mjiLr2UBGbwv7CUlnuIZJwtx4xqGernwrTvOisyh+2QzYTUoyyUvdjYv
bRaoysPe52DaWYSAVLeKR631ALz4WW2r6SWT+ku3nhaXnth5D7CxIvm1jG+xhbJI
XSCV8Q1KNpFrzzMqKpE
-----END PGP MESSAGE-----
```

**Comment by Valodim** [comment] 2017-01-09 15:24
Hi, thanks for your report! Can you send a message by the same method you used to send this one to me? -> look@my.amazin.horse

**Comment by sharpe5** [comment] 2017-01-09 22:52
Okay, done. 
- I used "Enable PGP/INLINE" to replicate the issue.
- I imported the email key "look@my.amazin.horse", and sent a test email with the subject "GitHub issue #1986".
- When I went into my "Send" items, in Windows Firefox + Mailvelope, it gave the same error as before.

**Comment by Hawk777** [comment] 2017-01-10 05:02
I can tell you with 99% certainty what the problem is. K9+OpenKeychain sends a PGP/Inline mail with the Content-Transfer-Encoding set to quoted-printable, but does not replace equals signs in the PGP encrypted armour blob with the string “=3D” as the quoted-printable standard requires. The quoted-printable encoding is decoded before passing the resulting text to GPG for decryption on a PC (at least this is the case in Claws, and I assume in Mailvelope and CryptUP as well).

PGP/MIME doesn’t suffer from this because K9+OpenKeychain set the Content-Transfer-Encoding to 7bit instead of quoted-printable.

**Comment by sharpe5** [comment] 2017-01-10 07:30
Good detective work, hopefully this is not a complex patch!

**Comment by Valodim** [comment] 2017-01-10 14:21
Ugh. Yeah, this is a problem with how K-9 handled Content-Transfer-Encoding. Fixed in https://github.com/k9mail/k-9/pull/2026

**Comment by dschuermann** [comment] 2017-01-10 15:29
@Valodim that was fast! 👍

**Closed by dschuermann** 2017-01-10 15:29 UTC
