### ISSUE TITLE
Expired key while just made

### ISSUE THREAD

**Issue by Yzord** [open-keychain/open-keychain#1983] opened 2017-01-07 21:34 UTC
I have two phones with k9 installed and Openkeychain. I used https://www.openkeychain.org/howto to configure both phones. So i created a key, uploaded it to the keyservers and downloaded the key of the other phone from the server.

So everything is set, but when i want to send mail with K9 (version 5.200) it gives me a weird error.

> Send failed: Revoked/Expired key cannot be used for sign or encryption

Both keys are brand new, so they are not revoked or expired (or Openkeychain must has its settings wrong).

Another strange part is this

Phone A (K9 5.200) gives the error above when i want to send the mail.
Phone B (K9 5.202) doesn't give an error and sends the mail to the other phone, but on the other phone i get:

> Security Warning: This message was signed by an expired key

So apparently both phones have expired keys. Help?

**Comment by Yzord** [comment] 2017-01-15 19:02
Anyone?

**Comment by juanminm** [comment] 2017-01-16 11:30
Did you look at the key with GnuPG natively on your computer and see if it says the key is expired? If it is on a public server and that public server have a Web frontend (like sks-keyservers.net) the expiration date should appear as well if you look it up with verbose information (vindex), it should be the sixth field or third date field on that keyserver.

**Comment by Yzord** [comment] 2017-01-16 13:52
Yeah, on sks-keyservers.net it shows no expiration date at all. Created 14 january 2017.

Revoked this one, created a new one, but still same problem. Really annoying :(

**Comment by Valodim** [comment] 2017-01-16 14:44
Sorry for not getting back to you sooner. Looking into it.

If you didn't use the now-revoked key anywhere, could you perhaps send it to me? -> `look@my.amazin.horse`

**Comment by Valodim** [comment] 2017-01-16 14:51
Oh actually I was able to reproduce. Working on this...

**Comment by Valodim** [comment] 2017-01-16 15:41
Scratch that, it was a different problem. The key doesn't show up as expired for me :\

**Comment by Yzord** [comment] 2017-01-16 16:22
Both keys are on the sks keyserver

5x (at) safe-mail.eu
6p (at) safe-mail.eu

5x has multiple keys on the server, but i know for sure i have the right key ID of it

**Comment by Valodim** [comment] 2017-01-16 16:39
Looked at the 6p key. As expected, there is no expiry there. I was also able to send a mail to you, nothing out of the ordinary. Hmh.

**Comment by Yzord** [comment] 2017-01-16 16:40
Personally it is the 5x key i believe

**Comment by Yzord** [comment] 2017-01-16 17:12
I have send you a screen recording

**Comment by dschuermann** [comment] 2017-02-08 19:57
Closing for now. We cannot reproduce

**Closed by dschuermann** 2017-02-08 19:57 UTC
