### ISSUE TITLE
Crash while decrypting with YubiKey and Ellyptic Curve

### ISSUE THREAD

**Issue by n0emis** [open-keychain/open-keychain#2590] opened 2020-09-13 20:01 UTC
## Expected Behavior

When trying to decrypt something when using a YubiKey and a ed25519 key, it should successfully decrypt.

## Current Behavior
Sometimes (I was not yet able to figure out when) the app crashes with the following stacktrace:
```
FATAL EXCEPTION: AsyncTask #3
Process: org.sufficientlysecure.keychain, PID: 6924
java.lang.RuntimeException: An error occurred while executing doInBackground()
     at android.os.AsyncTask$3.done(AsyncTask.java:354)
     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
     at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
     at java.util.concurrent.FutureTask.run(FutureTask.java:271)
     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
     at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.bouncycastle.math.ec.ECCurve org.bouncycastle.asn1.x9.X9ECParameters.getCurve()' on a null object reference
     at org.sufficientlysecure.keychain.securitytoken.operations.PsoDecryptTokenOp.getEcDecipherPayload(PsoDecryptTokenOp.java:203)
     at org.sufficientlysecure.keychain.securitytoken.operations.PsoDecryptTokenOp.decryptSessionKeyEcdh(PsoDecryptTokenOp.java:119)
     at org.sufficientlysecure.keychain.securitytoken.operations.PsoDecryptTokenOp.verifyAndDecryptSessionKey(PsoDecryptTokenOp.java:80)
     at org.sufficientlysecure.keychain.ui.SecurityTokenOperationActivity.doSecurityTokenInBackground(SecurityTokenOperationActivity.java:214)
     at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity.handleSecurityToken(BaseSecurityTokenActivity.java:439)
     at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity$1.doInBackground(BaseSecurityTokenActivity.java:149)
     at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity$1.doInBackground(BaseSecurityTokenActivity.java:137)
     at android.os.AsyncTask$2.call(AsyncTask.java:333)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     ... 4 more
 Force finishing activity org.sufficientlysecure.keychain/.ui.SecurityTokenOperationActivity
 Force finishing activity org.sufficientlysecure.keychain/.ui.DecryptActivitycoredns_zone_files_paths
```

## Steps to Reproduce (for bugs)

1. Put a ed25519 key on a YubiKey 5 NFC
2. Try to decrypt something with it

## Your Environment

* Android Version: 9
* Device Model: Moto G6
* OpenKeychain Version: 5.5
* From Google Play or F-Droid?: F-Droid

**Comment by e1mo** [comment] 2020-09-17 11:49
I'm having the same issues:

# Steps to Reproduce (for bugs)

1. Put a ed25519 key on a YubiKey 5 NFC
2. Try to decrypt something with it
3. Have it crash on 30% to 90% of the times-

# Your Environment

- Android Version: 9
- Device Model: OnePlus 5T
- OpenKeychain Version: 5.5
- From Google Play or F-Droid?: F-Droid

**Comment by andreasbrett** [comment] 2020-10-07 06:33
Same here. Yubikey 5 NFC with a ed25519 key.

## Your Environment
- Android Version: 9
- Device Model: OnePlus 3T
- OpenKeychain Version: 5.5
- From Google Play or F-Droid?: Google Play

**Comment by jess-sch** [comment] 2020-10-17 09:48
Seeing the same issue encrypting over USB with a YubiKey 5C with p384 keys.

# Steps to Reproduce
1. Generate p384 keys on a YubiKey 5C (on a computer)
2. Set up the YubiKey in OpenKeychain.
3. Sign & encrypt something to the key.
4. Have it either crash or silently close the activity.

# Your Environment
* Android Version: 11
* Device Model: Google Pixel 4
* OpenKeychain Version: 5.5
* From Google Play or F-Droid? Google Play

**Comment by espindola** [comment] 2020-10-18 23:53
I might be experiencing the same issue. How do I collect a backtrace on Android? I see the crash when trying to decrypt an email on k9.

Versions:
k9: 5.721
OpenKeychain: 5.5

**Comment by schch** [comment] 2020-12-14 00:17
Same Problem here. I played around with the code in 
org.sufficientlysecure.keychain.securitytoken.operations.PsoDecryptTokenOp.java

`    private byte[] getEcDecipherPayload(ECKeyFormat eckf, byte[] encryptedPoint) throws CardException {
        // TODO is this the right curve?
//        if (CryptlibObjectIdentifiers.curvey25519.equals(eckf.getCurveOID())) {
        if (eckf.getCurveOID().getId().startsWith(CryptlibObjectIdentifiers.curvey25519.getId())) {
            return Arrays.copyOfRange(encryptedPoint, 1, 33);
        } else {
            X9ECParameters x9Params = ECNamedCurveTable.getByOID(eckf.getCurveOID());
            if (x9Params == null)
                throw new CardException("Invalid OID for curve " + eckf.getCurveOID().getId()
                + " expected " + CryptlibObjectIdentifiers.curvey25519.getId());
            if (x9Params.getCurve() == null)
                throw new CardException("No curve for X9Params " + x9Params.toString()
                        + " and curve oid " + eckf.getCurveOID().toString());
            ECPoint p = x9Params.getCurve().decodePoint(encryptedPoint);
`

It works if you only check the beginning of the OID. For some reason the OID in eckf has an additional '.0' or '.99' at the end. I have seen both with the same Yubikey 5C.

**Comment by schch** [comment] 2020-12-14 16:28
I did some more digging. I looks like the last octet of all the key algorithm identifiers is random directly after inserting the USB key and then switches to 0 on further requests. The last byte sometimes is ignored by the ASN.1 decoder but 0 is always decoded. Therefore the OIDs match sometimes and the curve is identified, but most of the time it does not. I guess for NFC the value is always random as they are always initialized when held to the device.

```
        tag T   c1 L 0011 mV: 162b06010401da470f0176
        tag T   c2 L 0012 mV: 122b06010401975501050114
        tag T   c3 L 0011 mV: 162b06010401da470f01c7
```
Leads to `1.3.6.1.4.1.3029.1.5.1.20` for C2 and

```
        tag T   c1 L 0011 mV: 162b06010401da470f0172
        tag T   c2 L 0012 mV: 122b060104019755010501a4
        tag T   c3 L 0011 mV: 162b06010401da470f01ac
```

leads to `1.3.6.1.4.1.3029.1.5.1` for C2 and finally the 0 case

```
        tag T   c1 L 0011 mV: 162b06010401da470f0100
        tag T   c2 L 0012 mV: 122b06010401975501050100
        tag T   c3 L 0011 mV: 162b06010401da470f0100
```

which leads to `1.3.6.1.4.1.3029.1.5.1.0`

**Comment by dschuermann** [comment] 2021-02-23 17:22
Should be fixed with https://github.com/open-keychain/open-keychain/commit/2a0625e615e600e9645a5ac52520365ce469f08f

**Closed** 2021-03-17 11:47 UTC
