### ISSUE TITLE
Public not importable, signed/encrypted files unreadable with Yubikey, maybe(?) because of ECC master

### ISSUE THREAD

**Issue by crosser** [open-keychain/open-keychain#1454] opened 2015-07-19 14:59 UTC
Openkeychain 3.4.1 from the Playstore.

I created a new ed25519 master key on a disconnected machine, and three RSA2048 subkeys (sign, encrypt, authenticate) with GnuPG 2.1.3. I then successfully transferred subkeys to the Yubikey NEO, and exported public keys to a file.

I could successfully import public keys and create stubs for the private keys on another machine, (public keys even into gnupg 1.4).

    $ gpg2 -vv -K 8B19FA25
    gpg: using classic trust model
    gpg: key 8C3A5169: accepted as trusted key
    gpg: key 0155AEF9: accepted as trusted key
    gpg: key 8B19FA25: accepted as trusted key
    sec#  ed25519/8B19FA25 2015-07-17
    uid       [ultimate] Eugene Crosser (Evgeny Cherkashin) <crosser@average.org>
    uid       [ultimate] [jpeg image of size 10231]
    ssb   rsa2048/FB1C827C 2015-07-17
    ssb   rsa2048/F44F10F7 2015-07-17

    $ gpg2 -vv -k 8B19FA25
    gpg: using classic trust model
    gpg: key 8C3A5169: accepted as trusted key
    gpg: key 0155AEF9: accepted as trusted key
    gpg: key 8B19FA25: accepted as trusted key
    pub   ed25519/8B19FA25 2015-07-17
    uid       [ultimate] Eugene Crosser (Evgeny Cherkashin) <crosser@average.org>
    uid       [ultimate] [jpeg image of size 10231]
    sub   rsa2048/FB1C827C 2015-07-17
    sub   rsa2048/F44F10F7 2015-07-17
    
When I try to import the public key or select files to decrypt/verify, I get errors "No valid keys found" and "Encounted an error reading input data" respectively. When I touch the device with yubikey, it tries to get public keys from a keyserver and fails (I did not upload it - want to make sure that it works first!).

[Attachments: files and screenshots](https://drive.google.com/open?id=0ByShPJfR4k84fnJKa3ZEeloyZzQ1ZUViQVBLRVJZNmNkOE1wR2U4UXlMcWRHYUtLaFpWd00)

Please tell me if you need logcat or whatever else debugging data.

**Comment by Valodim** [comment] 2015-07-19 15:07
this is indeed due to the eddsa key, which are not supported at this point. and that's what gnupg means when it says eddsa keys are an experimental feature. this is being worked on as a GSoC project, I can't give you an ETA but hopefully we will have support or at least compatibility soon.

closing as duplicate of #1279.

**Closed by Valodim** 2015-07-19 15:07 UTC
