### ISSUE TITLE
Insecure encryption: an outdated algorithm has been used

### ISSUE THREAD

**Issue by ukoehler** [open-keychain/open-keychain#1618] opened 2015-12-06 20:14 UTC
Tried moving from AGP to open-keychain with k9-mail. It seems much more usable, however, I cannot verity signatures or decrypt messages. I always get 
Insecure encryption: an outdated algorithm has been used!
Interestingly, even for messages signed and encrypted with open-keychain. The signature verification and encryption work fine using AGP and KDE's Kontact on the same messages.

**Comment by richfirst** [comment] 2015-12-06 21:38
I have a similar issue:
am using version 3.7 of Openkeychain
My private key was created with a previous version of the program (probably the then-current version of Feb 2014).
I exported this key to my PC where I use Gpg4Windows to encrypt.

IMAP folder has the encrypted message that was generated on the PC  - K9 mail cannot decrypt the message with the Insecure encryption: outdated algorithm has been used message.

I read earlier this was by design in OpenKeyChain but it's a stunningly bad design decision in my opinion if that's the case. You could give a warning or something, but to refuse to decrypt is just plain unhelpful.

**Comment by dschuermann** [comment] 2015-12-06 21:42
Are you using the latest stable release of K-9 Mail?

**Comment by richfirst** [comment] 2015-12-06 21:48
I am (5.006) - but my issue might not be exactly same as OP -
I am able to decrypt the messages I send from K9 the have been encrypted with either my private or public key; I am NOT able to decrypt messages that were encrypted with my private key on my PC using GnuPG (GPG4Windows).

**Comment by ukoehler** [comment] 2015-12-07 10:29
Many thanks for the replies. Let me try to clear things up:
Android: AGP 1.1.1, K-9 Mail 5.006, OpenKeychain 3.7 
Linux: gpg (GnuPG) 2.0.26, libgcrypt 1.6.1

Form the comments above I see two problems:
1. Roundtrip test: OpenKeychain is not validating signature or decrypting emails I send to my second email address with OpenKeychain
2. Old encrypted email: Should I not be able to access my existing encrypted emails that I received over recent years, I cannot use OpenKeychain
Everything works fine with Linux. There doesn't seem to be a major problem with the generated emails. A warning about an outdated algorithm is great, but could be more detailed.

**Comment by dschuermann** [comment] 2015-12-10 14:26
This problem will be fixed in the next OpenKeychain version with https://github.com/open-keychain/open-keychain/commit/8dd63138266670295bbf081a97afa698a6a92a76 .
A better solution will be implemented in future version of K-9 Mail when a new version of our API is used.

**Comment by ukoehler** [comment] 2015-12-10 21:17
Great, I am really looking forward to that. Will be much more usable than APG.

**Closed** 2015-12-21 23:34 UTC
