### ISSUE TITLE
OpenKeychain won't assign a key to K9 account

### ISSUE THREAD

**Issue by chschtsch** [open-keychain/open-keychain#1394] opened 2015-07-01 20:27 UTC
I'm trying to set up encrypting in K9, but it doesn't seem to work.

Initially, after setting 'OpenPGP provider' option in K9 settings and trying to send my first mail encrypted with OK, it prompts OK to configure a new account for K9. After I set my key it returns to K9, but K9 pops 'OpenPGP Error: signing subkey not found!' toast immediately.
Then, when I try to assign my key manually in OK 'Apps' settings, it gives me 'Account has been saved', but again won't actually save.

BTW, didn't have such problem with APG.
Android 4.2.2, OpenKeychain 3.3 & K9 5.006

**Comment by Valodim** [comment] 2015-07-01 20:29
might be something with your key, can you tell me the key id?

**Comment by chschtsch** [comment] 2015-07-01 20:39
It's 0DEF4C5C.
OpenKeychain works fine, the only issue is an integration with K9.
What kind of problem you suppose it could be?

**Comment by dschuermann** [comment] 2015-07-05 21:29
Duplicate of #140

**Closed** 2015-07-05 21:29 UTC
