### ISSUE TITLE
Not able to search on custom keyserver

### ISSUE THREAD

**Issue by tigerwoods2k17** [open-keychain/open-keychain#2086] opened 2017-03-30 23:58 UTC
I am trying to search for keys on my custom sks keyserver, but everytime the result comes as failed.

I am able to upload my key to same server though!

What am I missing?

**Comment by TychoSchenkeveld** [comment] 2017-03-31 13:29
I have the same on mine. I usually export the keys in text format through the SKS web interface and then import them into OKC :)

**Comment by tigerwoods2k17** [comment] 2017-04-03 23:40
Can any senior developer provide an input on this? This is really bad if others are facing this issue too

**Comment by dschuermann** [comment] 2017-04-04 08:27
This is a duplicate of https://github.com/open-keychain/open-keychain/issues/2067. If you can provide a publicly reachable address of your server we could debug.

**Closed** 2017-04-04 08:28 UTC

**Comment by Valodim** [comment] 2017-04-04 12:22
Publicly reachable server that we can connect to and debug would be the way to go. Please email me at look@my.amazin.horse if you can help us out here.
