### ISSUE TITLE
Crash on key confirmation

### ISSUE THREAD

**Issue by countesscvs** [open-keychain/open-keychain#1894] opened 2016-06-29 23:47 UTC
Hello,

Today when going to compose an email I noticed that my contact, with whom I have a confirmed  key, was missing when inputting the name in the To section. I thought this odd.

I checked the contact card and indeed the keyo was missing. So, I opened the Open Keychain app to check the status. The key, which had been confirmed before,  was showing as unconfirmed.

I attempted to reconfirm the key to no avail. 

I deleted the key and used the QR Code to rescan. Still no confirmation.
Same with the search on the keyserver. Unconfirmed.

Everytime there is a popup saying there is an error & asks for a google error report or o force close.
When I choose force close, it does not. The screen simply flashes and returns to the unconfirmed key page.

Issue is only in this tablet.

See screenshots.
![screenshot_2016-06-29-19-15-25](https://cloud.githubusercontent.com/assets/14078434/16472428/00a0f6d8-3e32-11e6-9c13-3158af6c4164.png)
![screenshot_2016-06-29-19-15-33](https://cloud.githubusercontent.com/assets/14078434/16472443/09db71a6-3e32-11e6-91d8-ebcbc521a1f2.png)
![screenshot_2016-06-29-19-15-39](https://cloud.githubusercontent.com/assets/14078434/16472444/10807614-3e32-11e6-9335-49c5a67f6ef1.png)

**Comment by dschuermann** [comment] 2017-02-08 20:12
Duplicate of https://github.com/open-keychain/open-keychain/issues/2044

**Closed by dschuermann** 2017-02-08 20:12 UTC
