### ISSUE TITLE
Maintenance status of openpgp-api library

### ISSUE THREAD

**Issue by msfjarvis** [open-keychain/open-keychain#2432] opened 2019-01-03 13:40 UTC
This issue doesn't directly concern the app but is important to app developers integrating the library in their apps.

The [openpgp-api](https://github.com/open-keychain/openpgp-api) library, offered as the primary way to integrate with open-keychain, appears to be unmaintained. It was last committed to on 24 January 2018. Since then, a new version of Android has been released, and the entire support library architecture deprecated in favour of AndroidX, which has not been reflected in the library and is holding back development of apps utilising the library (for reference, zeapo/Android-Password-Store#467). There are trivial PRs on the repo that have been idling for 6 to 11 months with zero maintainer response. Has the library officially slipped into unmaintained status from your end? Is it time for users of the library to fork if they wish to continue using it for any modern apps?

**Comment by dschuermann** [comment] 2019-01-05 19:43
The library will be maintained as long as we maintain OpenKeychain, so it is definitely not deprecated :)

Until now there was no need to release a new version. The two pending pull requests weren't important, but I just merged them.

Do you have time to make an alternative OpenPgpPreference that is based on AndroidX in a pull request? We would definitely merge this.

**Comment by MSF-Jarvis** [comment] 2019-07-13 16:43
I've made some headway towards this but the DialogPreference API in AndroidX does not expose the same API surface that was used and abused in the legacy preferences. I've published my changes [here](https://github.com/MSF-Jarvis/openpgp-api/commits/master) for anybody who'd like to take over.

**Comment by msfjarvis** [comment] 2019-11-08 16:56
I've created [my own library](Kotlin X
Kotlin 100%) because openpgp-api has since returned to ignoring pull requests.

**Comment by Ashwin4RC** [comment] 2019-11-09 08:19
![images (5)](https://user-images.githubusercontent.com/40515149/68525466-cc8a1300-02f7-11ea-8b4d-8bba45c917b6.jpeg)

**Comment by MuntashirAkon** [comment] 2020-08-08 15:44
It's more than one and half a year since the issue is created, yet it is still using the deprecated libraries.

**Closed** 2021-10-15 04:54 UTC
