### ISSUE TITLE
Make Use of Fingerprint

### ISSUE THREAD

**Issue by jalcine** [open-keychain/open-keychain#1883] opened 2016-05-31 08:04 UTC
With the advent of API 23, we can now store secure information into the [Android Keystore][1]. For the ease of use of the client, storing their private key's password into the Android Keystore would allow for easier access. There's a [package][2] that makes this easy via [RxJava][3].

[1]: https://developer.android.com/training/articles/keystore.html
[2]: https://github.com/square/whorlwind
[3]: https://github.com/ReactiveX/RxJava

**Comment by dschuermann** [comment] 2016-05-31 13:38
duplicate of https://github.com/open-keychain/open-keychain/issues/1642

**Closed by dschuermann** 2016-05-31 13:38 UTC
