### ISSUE TITLE
Slow encryption and decryption times in app using OpenKeychain

### ISSUE THREAD

**Issue by untitaker** [open-keychain/open-keychain#1530] opened 2015-09-11 21:59 UTC
This is a repost from https://github.com/zeapo/Android-Password-Store/issues/119#issuecomment-139668816

Basically the problem is that the operations "finding the key and showing the auth dialog" and "decryption" take both an unbearable amount of time. Somehow I *nearly* resolved this issue by reimporting all my keys, but for other users it doesn't seem that easy.

My experience right now (after reimporting):

* When opening the show-password view of Password Store, it first shows a loading animation for 1-2 secs. During that time the process that takes the most CPU is `org.sufficientlysecure.keychain:remote_api`.

* "Authentication required shows within the current Password Store view, under the loading circle, with 1-2 seconds delay. The most-consuming process is `org.sufficientlysecure.keychain`.

* After 3-4 seconds, the password prompt from OpenKeychain pops up and the CPU activity goes back to normal/idle.

* **10 seconds** are taken for unlocking the key and decrypting. A lot of CPU activity is spent by the `org.sufficientlysecure.keychain:remote_api`-call (as told by @dirtYICE in the linked issue), but also some activity in `org.sufficientlysecure.keychain` itself.

cc @wongma7

**Comment by Valodim** [comment] 2015-09-14 12:54
Hi, thanks for your report!

This seems like a serious issue. The first question I have is, do you happen to have a large number of keys in your database? We did little in the way of optimizing database access so far, since the number of enties we deal with is usually small (< 100), so that might be it.

As a second guess, please try changing the password of you key in the edit key dialog *in OpenKeychain* to anything else (or even just back and forth to the same one).

If both of these don't apply/help, would you be up to profiling the process to provide us with data where all that time is really spent? I never experienced this issue, and am unsure at this point how we could reproduce it, so if we can't find the underlying problem with the ideas above, it would be tremendously helpful if you could provide us with that data.

**Comment by untitaker** [comment] 2015-09-14 13:05
I have two keys in my DB (excluding subkeys).

Not sure when I get around to trying that out, will report here if I did.

**Comment by DirtYiCE** [comment] 2015-09-14 13:17
@Valodim: currently I only have a single key (with two subkeys), so that shouldn't be a problem.

I've tried changing the password, but the edit button doesn't seem to work (it does nothing). Logcat says `I/ActivityManager(  918): START u0 {dat=content://org.sufficientlysecure.keychain.provider/key_rings/1835736119487791338/secret cmp=org.sufficientlysecure.keychain/.ui.EditKeyActivity} from pid 12615` but nothing happens.

**Comment by Valodim** [comment] 2015-09-14 13:30
Wait, the edit button doesn't work? That's uh, quite a problem itself.

**Comment by DirtYiCE** [comment] 2015-09-14 13:45
Hmm, looks like it's in a subpacket (the first secret key packet shows gnu-dummy S2K, and no protect count)

~~~
# off=610 ctb=9d tag=7 hlen=3 plen=966
:secret sub key packet:
        version 4, algo 1, created 1427558086, expires 0
        pkey[0]: [2048 bits]
        pkey[1]: [17 bits]
        iter+salt S2K, algo: 7, SHA1 protection, hash: 2, salt: BAC265D4C23F49DA
        protect count: 31457280 (238)
        protect IV:  0c dc 24 61 8e 36 bd 19 48 d8 a1 a4 7c 22 ab fc
        skey[2]: [v4 protected]
        keyid: 461B232D4ADF249C
~~~

By the way, I've created a logcat when trying to open the edit button with a debug version: https://gist.github.com/DirtYiCE/a836292f6aae0a5fd329

**Comment by Valodim** [comment] 2015-09-14 14:11
Ok I see the problem with edit key, if the master key is a dummy it doesn't work. That's sort of by design.

The 31457280 is a rather large number, can you change the passphrase in gpg using `--s2k-count 65536`, export, then see if that has any impact on the speed?

A little more info: secret keys are encrypted with their passphrase. the algorithm used for encryption is intentionally slow, because requiring 20 milliseconds to decrypt a key is no problem for usage, but increases the cpu time required for brute-forcing by a lot. The amount of "iterations" is variable, the larger the number the more cpu time required.

Now here's the problem: By default, gpg tests how many iterations it can perform in a fixed count of milliseconds (something like 20 iirc), and uses that number. This is fine as long as the machine this key is used on is comparable to the one running gpg. But with a strong x86 desktop cpu, this may lead to extremely poor performance on an energy-optimized mobile ARM architecture.

(Disclaimer: This is still only a guess as to what the problem is)

**Comment by DirtYiCE** [comment] 2015-09-14 14:31
Ok, gpg is still a magic for me. I run `gpg --s2k-mode 3 --s2k-count 65536 --edit-key <KEY_ID>`, type `passwd`, change the password, export with `gpg --export-secret-key <KEY_ID>`, and protection level is still 3145280...

**Comment by Valodim** [comment] 2015-09-14 15:38
that's better, but still a very long time. do you have an android sdk installed so you could profile this?

**Comment by DirtYiCE** [comment] 2015-09-14 16:47
Okay, I think I have created some traces. Unfortunately github doesn't let me attach it. But it looks like most of the time is spent inside spongycastle (org/spongycastle/openpgp/PGPSecretKey.extractPrivateKey) (93-96% of cpu usage is inside this).

**Comment by Valodim** [comment] 2015-09-15 11:58
OpenKeychain uses 524288 iterations (so 5*10^5) by default, we do not scale dynamically. that is still *a lot* smaller than the 3*10^7 your other key used, it really shouldn't take that long.

can you create a new key in openkeychain and see how that behaves? also, are we talking rsa2048 all around here?

**Comment by DirtYiCE** [comment] 2015-09-15 15:05
Yes, it was a 2048bit rsa key. I've generated a new key in OpenKeychain (with default settings, so it generated a 4096 rsa key). It now takes about 2.5s until the password dialog appears, and another 4s to actually decrypt.

**Comment by Valodim** [comment] 2015-09-16 11:24
do you have deeper info than that where time is spent inside bouncycastle? I suspect PGPUtil.makeKeyFromPassphrase, would appreciate if you could confirm this

**Comment by DirtYiCE** [comment] 2015-09-16 13:36
It says 96.6% Incl CPU time for PGPUtil.makeKeyFromPassPhrase.

**Comment by Valodim** [comment] 2015-09-16 15:15
Now that is some quality bug reporting, thanks! :+1: Now I have some good news and some bad news.

The good news: The critical code is divided into a lot of function calls. For instance, `LongDigest.processBlock` is called 343 times, but contains 6 methods which are called 80 times each, making for a whoopin' 180k stack frames which can be optimized away. Doing that makes the code very messy, and I'm not sure what the actual time save would be. Still, it's worth a try.

The bad news: There is nothing wrong with the code, and no actually big problem which hampers performance. We can optimize a little, but at the end of the day - the operation is just slow, which is the whole point of the iter+salt s2k encryption method. To solve this problem, we'd have to use a faster encryption 

I made a branch [s2k-optimize](https://github.com/open-keychain/open-keychain/tree/s2k-optimize) with the suggested optimizations. Care to compile that one and see if it makes any difference on your device?

On the long run, we might have to rethink our handling of s2k+iter encrypted keys...

**Comment by DirtYiCE** [comment] 2015-09-16 15:36
I've compiled it, it's a bit faster (but not really noticeable without a stopwatch...). May do another profiling if necessary.

By the way, decrypting directly from OpenKeychain instead of Password Store decrypting through the API is still faster. It takes about 1.5s for the password prompt to appear and about 2s to decrypt a 15kByte file. From password store it needs about 2s for the prompt to appear and 3s to actually decrypt (a few bytes).

**Comment by 1-eric** [comment] 2015-11-23 02:56
I have this problem as well.
It takes more than 2x40 seconds to decrypt a file on my phone running a CM-12.1 ROM.

The weird thing is that the same phone, the same key, the same encrypted file and the same version of OpenKeychain took less than 5 seconds on the original ROM of this phone (MIUI-7).

So, it looks like there is something in this CM-12.1 ROM that slows down decryption.
I'm frequently at a forum where the developer of this ROM is communicating with others... so, if someone here knows how this ROM can be fixed, tell me then I can post it there.

Are there other solutions (or work-arounds) to make decryption faster? Lower bits or less iterations?

:secret sub key packet:
        version 4, algo 1, created 1425311226, expires 0
        pkey[0]: [2048 bits]
        pkey[1]: [17 bits]
        iter+salt S2K, algo: 7, SHA1 protection, hash: 2, salt: 1451926AC9A4DAAD
        protect count: 3932160 (190)
        protect IV:  6d 26 84 c3 9c 79 96 7b ac d3 17 1d f4 9a b0 c2
        skey[2]: [v4 protected]
        keyid: 814EB8ABD601F283

**Comment by 1-eric** [comment] 2015-11-25 01:55
I've changed the protect count to 65536 and decryption is much much faster.

It was not easy to change the protect count because the newer versions of gpg (mine is gnupg-2.1.9) has a bug where the s2k-* command line and config file options are ignored, see: [issue1800](https://bugs.gnupg.org/gnupg/issue1800)

So after compiling and installing a older version (gnupg-1.4.19), I was able to use the s2k-count option when changing the passphrase.

**Comment by Valodim** [comment] 2015-11-25 18:31
This has really become more of a problem lately. However one of our bigger planned changes is to move away from individual passphrases entirely (#1541), so we probably won't do anything to fix this directly in the meantime.

**Comment by kiike** [comment] 2015-12-18 22:03
I could solve this issue with gnupg version 1. With version 2, just like @1-eric says, the `--s2k-*` options won't work. This is the process I followed:

1. Reencrypt the key

    gpg1 --s2k-mode 3 --s2k-count 65536 --edit-key
    [...]
    > passwd
    > save

2. `gpg1 --export-secret-keys KEYID > KEYFILE`

3. Deleting the OpenKeychain data (probably not necessary)

4. Import the key.

Now finding the key or decryption take way less time. Before more than one minute to find the key, then the password prompt would appear, and then after one minute the password would be shown by Pass. Now, the whole process takes less than 3 seconds. This is on a Sony Xperia P with Cyanogen Mod 11.

**Comment by dllud** [comment] 2015-12-18 22:53
In my case changing the password inside OpenKeychain did the trick and reduced both waiting times (before and after password input). I am working with an ECC key, perhaps that had to do with it. 

@Valodim As detailed on #1541 IMO you should go with "re-encrypt key and change protected count" solution. Asking for password on import is no big deal.
Actually that's what gpg2 does. I exported a private key from OpenKeychain and imported it with gpg2. gpg2 asked for the password and re-encrypted the key. The OpenKeychain key had a 524288 protected count. gpg2 increased it to 3276800 (the usual value on my x86 machine).

**Comment by 1-eric** [comment] 2015-12-22 22:16
I couldn't find where I can change the password. Maybe that option is not available for secret subkeys?

**Comment by gabm** [comment] 2016-01-14 18:55
I can confirm that shortening the s2k-count solves the problem and brings down the waiting time. I also couldn't change the password in OpenKeyChain due to a stripped master key, but @kiike's method worked very well. imho OpenKeyChain should re-encrypt the the key as @dllud pointd out. Is there a reason why the password cannot be changed when the master key is stripped?

**Comment by Valodim** [comment] 2016-01-14 20:33
Nope - that's a bug. Should be relatively simple to fix, pull requests welcome ;)

Same goes for the "should re-encrypt on import", which is certainly the way to go, it's just not implemented yet. this part is not quite trivial since it requires user interaction as part of the key import process.

**Comment by polyzen** [comment] 2016-01-15 03:10
Am I correct in understanding the s2k-count can be shortened by changing the key's password via OpenKeyChain?

**Comment by Valodim** [comment] 2016-01-15 09:40
Yup

**Comment by polyzen** [comment] 2016-01-15 14:20
Thank you.

**Comment by gabm** [comment] 2016-01-17 09:41
Ok guys, here are the two problems that still exist (for clarification): 
1) The key's password cannot be changed when the masterkey is stripped
2) When a key is imported, we want to change the protection count to a more suitable value

I am currently developing a bugfix for the first problem after discussing a possible way with @Valodim. Basically I will implement a dedicated "ChangePassword"-function in PGPKeyOperation.java. The second problem requires a password-prompt on import to unlock the imported key so that the s2k-count can be shortened.

**Comment by dschuermann** [comment] 2016-01-17 21:19
@gabm I opened a issue for 1) https://github.com/open-keychain/open-keychain/issues/1692 please move related discussion into this one.

**Comment by Valodim** [comment] 2016-03-13 14:32
I hear that #1708 brought performance to a reasonable level, closing this for now

**Closed by Valodim** 2016-03-13 14:32 UTC
