### ISSUE TITLE
Error on SSH usage with NitroKey

### ISSUE THREAD

**Issue by nonbinary** [open-keychain/open-keychain#2538] opened 2020-04-09 11:47 UTC
I've tried to log in to two different servers using my PGP smartcard as a SSH key, with connectbot and password store. Both give me the following error:

Publickey authentication failed.
Error signing challenge: Exception in executeApi call : Attempt to invoke virtual method 'long org.bouncycastle.openpgp.
PGPPrivateKey.getKeyID()' on a null object reference

I can log in with Linux with the key, and OpenKeychain can use the key to decrypt mails. I've successfully used the key on android before on another phone.
I'm using a Fairphone 3 with stock Android 9.

**Comment by n0emis** [comment] 2020-07-02 23:49
I have the same problem with the YubiKey 5NFC. My key uses ed25519.

**Comment by n0emis** [comment] 2020-07-02 23:52
Here is a stacktrace: 
```
SshAuthenticationApi: Exception in executeApi call
SshAuthenticationApi: java.lang.NullPointerException: Attempt to invoke virtual method 'long org.bouncycastle.openpgp.PGPPrivateKey.getKeyID()' on a null object reference
SshAuthenticationApi: 	at android.os.Parcel.createException(Parcel.java:1956)
SshAuthenticationApi: 	at android.os.Parcel.readException(Parcel.java:1918)
SshAuthenticationApi: 	at android.os.Parcel.readException(Parcel.java:1868)
SshAuthenticationApi: 	at org.openintents.ssh.authentication.ISshAuthenticationService$Stub$Proxy.execute(ISshAuthenticationService.java:7)
SshAuthenticationApi: 	at org.openintents.ssh.authentication.SshAuthenticationApi.executeApi(SshAuthenticationApi.java:2)
SshAuthenticationApi: 	at com.zeapo.pwdstore.git.config.SshApiSessionFactory$ApiIdentity.getSignature(SshApiSessionFactory.java:7)
SshAuthenticationApi: 	at com.jcraft.jsch.UserAuthPublicKey.start(UserAuthPublicKey.java:67)
SshAuthenticationApi: 	at com.jcraft.jsch.Session.connect(Session.java:96)
SshAuthenticationApi: 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:13)
SshAuthenticationApi: 	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:7)
SshAuthenticationApi: 	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:2)
SshAuthenticationApi: 	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:1)
SshAuthenticationApi: 	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:1)
SshAuthenticationApi: 	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:20)
SshAuthenticationApi: 	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:23)
SshAuthenticationApi: 	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:42)
SshAuthenticationApi: 	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:4)
SshAuthenticationApi: 	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:1)
SshAuthenticationApi: 	at com.zeapo.pwdstore.git.GitAsyncTask.doInBackground(GitAsyncTask.kt:44)
SshAuthenticationApi: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
SshAuthenticationApi: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
SshAuthenticationApi: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
SshAuthenticationApi: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
SshAuthenticationApi: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
SshAuthenticationApi: 	at java.lang.Thread.run(Thread.java:764)
SshAuthenticationApi: Exception in executeApi call : Attempt to invoke virtual method 'long org.bouncycastle.openpgp.PGPPrivateKey.getKeyID()' on a null object reference

```

**Comment by elijahmathews** [comment] 2020-09-11 19:07
Also running into this issue with a `ed25519` authentication subkey stored on a Yubikey 5 NFC (and the identical error message on [Android Password Store](https://github.com/android-password-store/Android-Password-Store)), even though it works for SSH authentication in GnuPG 2.2.20.

**Comment by msfjarvis** [comment] 2021-02-05 06:58
We have a bunch of people facing issues with ed25519 over at Android Password Store, any pointers as to where I can start looking for the root cause?

**Comment by n0emis** [comment] 2021-02-05 07:50
There is already a pr, which might close this: https://github.com/open-keychain/open-keychain/pull/2631

**Closed** 2021-03-16 14:48 UTC
