### ISSUE TITLE
Could you tell me why OpenKeychain auto stripped secret key without confirm?

### ISSUE THREAD

**Issue by iseki0** [open-keychain/open-keychain#2466] opened 2019-06-20 16:23 UTC
Is it by designed? When I insert YubiKey to Android Phone, the secret key has been remove with no alert or confirm. Now I lost my all secret key... Even cannot revoke.

Maybe we should add a clearly confirm and alert before auto stripped secret key?

Thank you.

**Comment by CueHD** [comment] 2019-07-22 16:22
Secret keys are never transferred off of the YubiKey. This is by design of the YubiKey. You should still be able to perform all actions which require the secret key, but you must use the YubiKey to do so.

**Comment by cpdyj** [comment] 2019-07-23 01:29
It's so crazy that OpenKeyChain transfer key to YubiKey without any notice. Not copy, it moved.😲😲😲

**Closed** 2022-09-28 16:19 UTC
