### ISSUE TITLE
keys.openpgp.org is not set by default and keys can not be found

### ISSUE THREAD

**Issue by malo44** [open-keychain/open-keychain#2562] opened 2020-06-09 19:37 UTC
According to the changelog, keys.openpgp.org should be used as key server by default starting with version 5.3. This is definitely not the case. If you enter hkps://keys.openpgp.org afterwards and put it on the first position, no keys will be found. Nothing works with vks://keys.openpgp.org. This error appears: invalid url.

## Expected Behavior
keys.openpgp.org should be used as keyserver by default.
You should be able to search and find keys via this keyserver

## Current Behavior
When I search for a key that I know is on this keyserver, I get the following error message: "No key found." and "An error occurred while searching the key"

## Steps to Reproduce (for bugs)

1.1. Use hkps://keys.openpgp.org as keyserver 
1.2. Put this server in the first place
1.3. Search a known key

2.1 Enter  vks://keys.openpgp.org as keyserver 
2.2 Try to establish a connection

## Your Environment

* Android Version:  LinageOS 17.1 (Android 10) 
* Device Model: BQ Aquaris Pro
* OpenKeychain Version: 5.5
* From Google Play or F-Droid?: FDroid

**Comment by edeustua** [comment] 2020-06-17 18:38
Same issue here. Oneplus 5 OxygenOS 10.0 (Android 10). Google Play OpeKeychain version 5.5.

**Comment by crazyscientist** [comment] 2020-07-22 14:23
+1

**Comment by grosshad** [comment] 2020-07-22 18:44
Same here
Can add sucessfully hkps://keys.openpgp.org as only keyserver 
![Screenshot_20200722-202545](https://user-images.githubusercontent.com/68660971/88214903-2bf83b00-cc5b-11ea-89b1-ace597f12ef0.png)

and use it to update keys already present in OpenKeychain. 
![Screenshot_20200722-203024](https://user-images.githubusercontent.com/68660971/88215012-55b16200-cc5b-11ea-85e3-819e96fa7ded.png)

But this does not return anything by trying to add some new Keys, evey time getting Error
![Screenshot_20200722-203102](https://user-images.githubusercontent.com/68660971/88215228-9f9a4800-cc5b-11ea-8e91-a883b52f5354.png)

Cannot add vks://keys.openpgp.org as ist rejected as unkown URL
![Screenshot_20200722-204347](https://user-images.githubusercontent.com/68660971/88215542-1cc5bd00-cc5c-11ea-9c93-5195aa8b084c.png)

**Comment by grosshad** [comment] 2020-07-22 19:50
Duplicate of #2499

**Comment by wurstsemmel** [comment] 2020-11-17 15:36
My Environment:
- Android Version: OneUI 2.5 (Android 10)
- Device Model: Samsung Galaxy S9
- OpenKeychain Version: 5.5 (55000)
- From Google Play or F-Droid?: Google Play

The keyserver keys.openpgp.org is not set as default in OpenKeychain. After adding it manually, I cannot find keys in OpenKeychain. I tried it with an email address with a key on keys.openpgp.org (verified via its webinterface).

**Closed** 2021-02-17 12:13 UTC
