### ISSUE TITLE
No way to decrypt text/plain using explicit Intent

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1421] opened 2015-07-07 21:13 UTC
From the Mailinglist:
```
Were there any changes made to the available intents recently?  I have been using an intent sent from Tasker to decrypt PGP message text received via SMS.  By sending this intent, it would start openkeychain, decrypt the passed ASCII armored text string and display the decrypted message on screen in OpenKeychain.  It recently stopped working, but I don't know if it's because I upgraded my phone to Lollipop, or because OpenKeychain updated/changed.

Here's the intent info that I was previously successfully sending:

Action:  android.intent.action.SEND
Package:  org.sufficientlysecure.keychain
Class:  org.sufficientlysecure.keychain.ui.DecryptTextActivity
Mime Type:  text/plain
Extra:  android.intent.extra.TEXT:[[ASCII_ARMORED_PGP_MESSAGE_GOES_HERE]]


I don't remember exactly where I came up with those intent values, as it was a combination of various sources I found online and plenty of trial & error to arrive at a working set of values.  BTW, I'm not a proper android developer, I'm just pretty good at using my google-fu to kludge together scripts/etc that do what I want 

Any help or advice would be greatly appreciated!


I'm running Android 5.1.1 (CM12) on Samsung GS3 (SCH-I535) with OpenKeychain v3.4
```

We removed the EXTRA here: https://github.com/open-keychain/openkeychain-intents/commit/9b5b0b9ca32e80f3dadebe57d27e1422889d8254

I think we should re-add a way to make it possible to send text to OpenKeychain by allowing ``org.sufficientlysecure.keychain.action.EXTRA_TEXT`` for our generic decrypt action ``ENCRYPT_DATA``

BTW: https://github.com/open-keychain/openkeychain-intents/blob/master/README.md also needs an update!

**Comment by dschuermann** [comment] 2015-07-07 21:26
Just looking at it:
What he wants to do is already possible with changing the class to ``DecryptActivity``. Still I think it should be better to support a stable API for this.

**Comment by Valodim** [comment] 2015-07-07 22:08
I removed our EXTRA_TEXT because it's essentially a duplicate of the EXTRA_TEXT used by android's standard ACTION_SEND. I wouldn't mind if the extra got re-added, but given that the number of affected people is likely very small, I would prefer enforcing a move to the standard ACTION_SEND interface.

**Comment by dschuermann** [comment] 2015-07-08 09:32
I disagree. Setting a specific class is not a stable API, because the class name can change with a new version.
Also we should encourage that people set the package explicitly with http://developer.android.com/reference/android/content/Intent.html#setPackage(java.lang.String) to enforce that OpenKeychain handles the Intent and not some malicious app.

**Comment by dschuermann** [comment] 2015-07-08 09:40
Looks like if he does it with DecryptActivity as a class, the content is not recognized as text/plain and thus no "View in OpenKeychain" is available:

```

Using org.sufficientlysecure.keychain.ui.DecryptActivity for the class kind of works - OpenKeychain v3.4 now responds to the intent, but doesn't display the text on screen like it used to.  I'm prompted with a "<no filename>" entry on screen that I'd have to manually save somewhere, then open with a text viewer and view the decrypted contents, which seems a bit clunky as compared to the behavior in v3.2.3 and prior.  

http://i.imgur.com/1JR1gzl.png

Contents of Export.log:
[DEBUG]Starting decrypt operation…
    [DEBUG]Found block of asymmetrically encrypted data for key 0xd7d8d163064089bd
        [DEBUG]Using password from cache
    [DEBUG]Preparing streams for decryption
        [INFO]Unlocking secret key
    [DEBUG]Processing cleartext data
            [DEBUG]Unpacking compressed data
            [DEBUG]Processing literal data
                    [DEBUG]MIME type: application/octet-stream
                    [DEBUG]Modification time: Tue Jul 07 15:03:58 CDT 2015
            [INFO]Integrity check OK!
            [OK]Decryption/Verification finished

```

**Comment by Valodim** [comment] 2015-07-08 11:17
I see. I would propose here an EXTRA_TEXT_DISPLAY which directly opens the text file if set to true and the type is text/plain. sound good?

This sort of extra cannot work for any other file type though, text/plain is special because we handle it ourselves and can display its encrypt/sign status next to the text.

**Comment by numericOverflow** [comment] 2015-08-11 21:51
@Valodim - The EXTRA_TEXT_DISPLAY sounds like a good option.  I've had to hold off on updating to the v3.4 release because the missing EXTRA_TEXT means I can't pass OKC encrypted text on the fly.  I'd really love to see this ability added back!

**Comment by numericOverflow** [comment] 2015-10-19 14:36
Any update on fixing the ability to decrypt plain text to screen?  I need it badly, and can't upgrade beyond v3.2.3 without losing this ability.

**Comment by Valodim** [comment] 2015-10-21 20:37
Changed behavior, text is now directly shown if it is the only encrypted/signed data part, and is not too long (cf. #1503)

7eb9f5d5cfb3e735076ea019013f89ca60ed5804

**Comment by numericOverflow** [comment] 2015-10-26 15:59
With v3.6, the plaintext is still not shown after decryption for me.  I've tried sending the ASCII armored string [1] via a Tasker Intent, and also [2] via Decrypt > Read from clipboard.  Both methods produce the same result.

I am presented with a screen with an unknown filename, rather than the plaintext.  Decryption succeeds per the log file, and if I manage to share the file with a text editor (which is very difficult due to the "[really_long_GUID].null" file name that is output) I can eventually get the plaintext.

My original plaintext message is only 2 lines long with under 100 characters, so it shouldn't be too long to display.

See screenshot here:  http://i.imgur.com/Co9UUi0.png
--------------------------------
>[START] Processing input data
>[DEBUG] Attempting to process OpenPGP data
>  [DEBUG] Starting decrypt operation…
>   [DEBUG] Found block of asymmetrically encrypted data for key xxxxxxxxxxxxxx
>    [DEBUG] Using password from cache
>    [INFO] Unlocking secret key
>   [DEBUG] Preparing streams for decryption
>   [DEBUG] Processing cleartext data
>     [DEBUG] Unpacking compressed data
>     [DEBUG] Processing literal data
>       [DEBUG] Modification time: Sun Oct 25 20:00:00 CDT 2015
>       [DEBUG] MIME type: application/octet-stream
>     [INFO] Integrity check OK!
>     [OK] Decryption/Verification finished
>[DEBUG] Parsing MIME data structure
>  [DEBUG] No MIME structure found
>[OK] Data processing successful

**Comment by numericOverflow** [comment] 2015-10-26 16:03
Derp, I hit submit too quickly.... one last bit:

@Valodim - does it matter that my data is only encrypted & not signed?  FWIW, I can't re-open this ticket because it was actually created on my behalf by @dschuermann .

**Comment by Valodim** [comment] 2015-10-26 16:08
this is a metadata problem: the text view is only shown if openkeychain has an indication that the content is actually text data.

pgp encrypted data comes with a flag which can be `b` (binary), `t` (text) or `u` (unicode), and in your files it is `b`, so the file is treated as binary. if you use gpg to encrypt your data, just use the  `--textmode` parameter to flag the data as text, and everything should work fine.

**Comment by numericOverflow** [comment] 2015-10-26 20:17
@Valodim - adding the --textmode flag made it work, now using v3.6 I'm able to get text shown onscreen when using intents/clipboard.

Thanks much for all your efforts!

**Comment by Valodim** [comment] 2015-10-26 20:18
alrighty! closing the issue, then :+1:

**Closed by Valodim** 2015-10-26 20:18 UTC
Labels: bug
