### ISSUE TITLE
can't add keys.openpgp.org and also not set as default

### ISSUE THREAD

**Issue by webratte** [open-keychain/open-keychain#2499] opened 2019-10-10 20:33 UTC
- Platform (android/blackberry/anbox): Android 7.0
- Device: Huawei nova
- OpenKeyChain Version: 5.3 from Google Playstore
- Expected behavior:  Use keys.openpgp.org as default keyserver

- Actual behavior: This server ist not shown in the server list and I also can't add it.

I tried it by installing OpenKeyChain from the scratch.

Both sceenshots are directly after installing.

![Screenshot_20191010-222558](https://user-images.githubusercontent.com/6864851/66604064-a9abf800-ebad-11e9-8762-7fb325c362eb.png)
![Screenshot_20191010-222739](https://user-images.githubusercontent.com/6864851/66604078-b3cdf680-ebad-11e9-8064-0cd2b2cac5c1.png)

**Comment by mark-orion** [comment] 2020-01-17 17:05
Same problem here. In addition to this I cannot update keys from the keyservers. All attempts fail with an "SSL ProtocolExeption". I wonder if Android 7.0 is to blame here: https://issuetracker.google.com/issues/37122132
However if this bug is the case, then maybe OpenKeychain could request a cipher suite that is supported by Android 7.0

**Comment by grosshad** [comment] 2020-07-22 19:48
Duplicate of #2562

**Comment by domfi** [comment] 2021-01-31 18:10
Same Problem on Google Pixel 5 With Android 11. It's not possible to add keyserver. Tests of the predefined keyservers also fail.
Import of keys (via token) depend on the keyservers, so the import of the keys from my Yubikey fails.

**Comment by felixzwettler** [comment] 2021-02-08 10:10
Same here on Xiaomi Mi 9 SE with MIUI 12. It always gives me the error "connection to keyserver failed." when i try to add "hkps://keys.openpgp.org" to the keyserver list.

**Comment by Valodim** [comment] 2021-02-08 10:13
This was an issue with CRLs in bouncycastle's TLS. Will be fixed in an upcoming release, sorry for the inconvenience.

**Closed by Valodim** 2021-02-08 10:13 UTC
