### ISSUE TITLE
Offer decrypt action for e.g. .asc files

### ISSUE THREAD

**Issue by SaschaZorn** [open-keychain/open-keychain#1043] opened 2015-02-16 22:49 UTC
Besides the "Import Key with OpenKeychain" Action, it would be nice to have a "Decrypt with OpenKeychain" Action. (or even better just "Open with OpenKeychain" and let OpenKeychain decide or offer a selection what to do with it, based on the content that file)

This would be EXTREMELY helpful to mitigate shortcomings in Mailers that do not support PGP/MIME (as K9 does for over a year - https://code.google.com/p/k9mail/issues/detail?id=5864). One would be able to at least decrypt the message more easily (without storing it first, opening OpenKeychain, select decrypting and search for the file, ...)

**Comment by Valodim** [comment] 2015-02-18 10:18
The "Decrypt with OpenKeychain" action exists, and is associated with *.asc, *.gpg, *.pgp and *.bin files the same way the "Import with OpenKeychain" action is (see [manifest](https://github.com/open-keychain/open-keychain/blob/development/OpenKeychain/src/main/AndroidManifest.xml))

getting those intent filters right so that they are recognized correctly in all scenarios is a little tricky. can you be more specific where exactly it doesn't work for you? is that opening an attachment from k9?

**Comment by SaschaZorn** [comment] 2015-02-18 10:24
Exactly. Opening the file "encrypted.asc" from K9 only shows "import key". I guess the issue is the mime-type matching.
DecryptTextActivity is:
"text/*
"message/*

DecryptFilesActivity is:
"application/pgp-message"

But my attachments (received from Thunderbird + Enigmail and Posteo.de "inbound server encryption") are unfortunately of type:
"application/pgp-encrypted"

**Comment by Valodim** [comment] 2015-02-18 12:05
The "application/pgp-encrypted" mime type does not contain any data, only "Version: 1" (see [RFC3156](https://tools.ietf.org/html/rfc3156) for details), the actual encrypted data has mimetype "application/octet-stream", which is correctly listed in the manifest ([line 248](https://github.com/open-keychain/open-keychain/blob/development/OpenKeychain/src/main/AndroidManifest.xml#L248)).

If K9 is sending an intent with mimetype "application/pgp-encrypted", that would be a problem

**Comment by SaschaZorn** [comment] 2015-02-18 12:47
Sorry...my error. I have been fooled by the UI that cut of the rest of the multipart stuff...

You are absolutely right. The file is shipped as:
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

But anyways, I just see "Import Key with OpenKeychain".

I've never done Android development, so I'm not sure if this helps, but Logcat only shows this intent with text/plain:
I/ActivityManager(  953): START u0 {act=android.intent.action.VIEW dat=content://com.fsck.k9.attachmentprovider/fbc1d5a0-f8f9-41b8-b6ce-4dd5c03c9c62/40/VIEW typ=text/plain flg=0x80001 cmp=android/com.android.internal.app.ResolverActivity} from pid 25347

Unfortunately I don't see any Resolver.

Can I help you debugging this issue any further?

**Comment by SaschaZorn** [comment] 2015-02-18 12:50
Decrypt action is missing:
 <data android:mimeType="*/*" />

Could this be the cause? K9 does not properly send the Mime type, and Decrypt only works certain Mime-Types, as ImportKey works on mimeType */*.

**Comment by SaschaZorn** [comment] 2015-02-18 12:56
Actually its the other way round...

intent_import_key is missing 
>\<data android:mimeType="\*/\*">
and is working correctly.

Seems like this \*/\* is not working.

**Comment by Valodim** [comment] 2015-02-18 16:33
Ascii-armored data labeled as text/plain is probably a common case indeed. @dschuermann has more experience with the intent filters than me, so I'll leave this to him. Chances are this is the right idea and it'll be fixed in the next release. Thank you for your report :+1:

**Comment by kumzugloom** [comment] 2015-03-04 07:11
Hi,
I also have this issue. 
But even when I store the .asc file (created with a Thunderbirds Enigmail with PGP/MIME activated) and open it for encryption with open-keychain it states "Keine gültigen Signaturdaten gefunden!" (No valid signature data found) and therefore does not complete the decryption.
Therefore I cannot open this type of message at all on my mobile device.

I'm using: 
Cyanogenmod 11-20141115-SNAPSHOT-M12_mako, Android 4.4.4, 
K9-Mail 5.002, 
open-keychain 3.1.2

**Comment by dschuermann** [comment] 2015-03-04 09:56
As far as I remember, I removed the intent filter due to https://github.com/open-keychain/open-keychain/issues/290 .
The real fix for this issue is to finish the PGP branch of K-9: https://github.com/k9mail/k-9/commits/pgp_mime_preparations . So please wait until we are done with K-9 improvements.

**Comment by alanthehat** [comment] 2015-03-04 17:26
@dschuermann is there an estimated timeline for K-9?

**Comment by dschuermann** [comment] 2015-03-04 17:40
@alanthehat no

**Comment by dschuermann** [comment] 2015-05-05 07:26
I just reconfirmed the problem. The files are broken due to bug https://github.com/open-keychain/open-keychain/issues/290
I also reformatted the issue to make it more clear what the problem is.

**Closed by dschuermann** 2015-05-05 07:26 UTC
Labels: bug

**Comment by vanitasvitae** [comment] 2015-05-17 15:27
Are you still working on a solution? I cant decrypt some messages which appear to be empty and just have two files attached: encrypted.asc and noname.pgp.

**Comment by Valodim** [comment] 2015-05-17 18:34
the issue raised here is not something we could work on on our side, the AOSP mail client tries to process the data and what we get sent is corrupted beyond repair (see #290 for details)

k-9 pgp/mime is not ready, and won't be for a while. very rough estimate it's half a personyear of work left, which neither of us have enough free time to spend.

so the short version is, we'd like to see this done too, but we can't give an estimate on when that might happen.

**Comment by vanitasvitae** [comment] 2015-05-17 19:15
Okay thanks for the info :)

**Comment by jmaurice** [comment] 2015-05-27 04:16
wow, half a year of work? that sounds a bit much, especially considering the minimal "mimegpg" utility included sqwebmail is only a few hundred lines of C code:
http://fossies.org/dox/sqwebmail-5.8.2/mimegpgheader_8c_source.html

**Comment by clawoflight** [comment] 2015-05-27 06:58
The problem is that a lot of the backend architecture of k9 has to be redone for this change. The actual pgp/mime functionality is only a relatively small portion of the work AFAICT.

**Comment by dschuermann** [comment] 2015-05-27 07:02
Exactly, and no one is working full time on any of the projects. Thus, @Valodim 's estimate is actually very positive.

**Comment by dolohow** [comment] 2015-08-27 07:42
Still in lates version from F-Droid

**Comment by clst** [comment] 2015-10-20 20:36
That's too bad. That means there is no (easy) way to read encrypted mail sent by facebook. :(
pgp plaintext works fine...

**Comment by Valodim** [comment] 2015-10-21 07:25
Read-only of encrypted PGP/MIME mails in K-9 mail will hopefully work acceptably in the upcoming version :+1:

**Comment by vanitasvitae** [comment] 2015-10-21 08:50
Oh nice. Did someone do the rework of K9's backend architecture?

**Comment by Valodim** [comment] 2015-10-21 12:47
Sorry, this was misleading. It won't work in K-9 itself, but the `.asc` files can be opened in OpenKeychain, which will also parse the MIME structure so attachments can be viewed etc.

**Comment by alanthehat** [comment] 2015-10-22 00:07
Am I right in thinking that 'encrypted.asc' contains a complete email message with all attachments & HTML variants etc? 
And that the version of OpenKeychain that you are working on will decrypt this & separate the parts? 
Is this also true for 'noname.asc'?

**Comment by Valodim** [comment] 2015-10-22 22:30
yup. and that version was released earlier today, give it a shot

**Comment by demure** [comment] 2015-10-22 22:37
Sweet. Seems to work for me ^__^

**Comment by alanthehat** [comment] 2015-10-24 05:17
Looking forward to it appearing on F-Droid :-) 
Thanks for your hard work
