### ISSUE TITLE
Request: make used langauage selectable

### ISSUE THREAD

**Issue by Diapolo** [open-keychain/open-keychain#1491] opened 2015-08-19 10:33 UTC
Reasons:

1. Makes ist easier to see context when translating via Transifex.
2. Ensures I don't have to see unprofessional parts of german translation that sneaked in, because I took a translation break ^^.

**Comment by dschuermann** [comment] 2015-08-19 10:39
Duplicate of https://github.com/open-keychain/open-keychain/issues/215

**Closed by dschuermann** 2015-08-19 10:39 UTC
