### ISSUE TITLE
Crash when validating key with Yubikey

### ISSUE THREAD

**Issue by evilstiefel** [open-keychain/open-keychain#1326] opened 2015-06-03 11:37 UTC
When I wan't to verify a fingerprint (manually display and compare), I am unable to complete the process. After confirming the fingerprint matches and selecting my key (which is stored on the Yubikey), the application just crashes when hitting the button to complete the process.

My setup: non-default Yubikey-Pin (but it doesn't matter, happens with the default PIN as well), only one personal PGP-Key imported to Openkeychain.

In the Report (which unfortunatelly I cannot export), the top-most stacktrace entry says:
java.lang.AssertionError: Unhandled SecretKeyType (should not happen).
![screenshot_2015-06-03-13-35-58](https://cloud.githubusercontent.com/assets/8029370/7959027/904960b2-09f5-11e5-834a-9a285a49cbbd.png)

**Comment by dschuermann** [comment] 2015-06-03 11:38
Thanks for your report.
Looks like a duplicate of https://github.com/open-keychain/open-keychain/issues/1262
Please create a comment at https://github.com/open-keychain/open-keychain/issues/1262.

**Closed by dschuermann** 2015-06-03 11:38 UTC
