### ISSUE TITLE
Key server status: unknown?

### ISSUE THREAD

**Issue by crashlyrics** [open-keychain/open-keychain#2633] opened 2021-01-05 17:51 UTC
After importing a key pair in Openkeychain via encryted Mail (FairEmail) and confirming it with the password, the app shows the key as "key server status unknown", whereas 2 other key pairs I imported before show: "not published". I can't remember having done anything different. Is there way to switch the message to "not published" by any means or did I something wrong and may I repeat the procedure? Thank you.

* Android Version: 10
* Device Model: Moto g8
* OpenKeychain Version: 5.5
* From Google Play or F-Droid?: F-Droid

**Comment by crashlyrics** [comment] 2021-01-05 22:34
Also testing the new key encrypting an email worked fine, but it used the signature of another key with another identity(?) and it only offers me this other identity. Seems all a bit weird ...

**Comment by MaxEtMoritz** [comment] 2021-01-29 10:54
For the "status unknown" message, try heading to the details page of the key in Question and click the circle arrow at the top, next to the three dots. that should refresh the published status.

**Comment by crashlyrics** [comment] 2021-01-29 11:49
Then it looks up for key server doesn't find a key (or doesn't get access, because it asks for network connection ...?). The key was never ever published at all (so it's no surprise). But I have two other keys, where the status was recognized correctly (not published). Only this one makes trouble for some reason, though I did just the same as with the others ...
-----------------------------------------------
email + xmpp xchange@disroot.org
-----------------------------------------------

29.01.2021 11:54:25 Markus Oppmann <notifications@github.com>:

**Comment by MaxEtMoritz** [comment] 2021-01-29 12:37
If the network connection error says CertificateException, you experience issue #2638 (like me, too). I Don't know what's wrong there, sorry. Try to change your main Key server to the sks pool, that worked for me.

**Comment by Valodim** [comment] 2021-01-29 12:37
This was an issue due to failed CRL checks in BouncyCastle's TLS provider. I updated the version we use, this should be fixed soon.

**Comment by Valodim** [comment] 2021-01-29 12:38
Closing as duplicate of #2638 (and probably others) so we don't repeat this information in multiple places :)

**Closed by Valodim** 2021-01-29 12:38 UTC
