### ISSUE TITLE
Not ignoring CRC errors

### ISSUE THREAD

**Issue by jschwartzentruber** [open-keychain/open-keychain#1917] opened 2016-08-18 15:58 UTC
CyanogenMod: 13.0-20160816-SNAPSHOT-ZNH5YAO0F8-hammerhead
K-9 Mail: 5.010
OpenKeychain: 4.1 (41010)

I have an RSA 8192-bit key I use with Thunderbird/Enigmail without issue. I recently set up K-9 and APG and that also worked without issue. I just read on K-9's site that APG is unmaintained and installed OpenKeychain instead, imported the same key, pointed K-9 at OpenKeychain, and now I'm getting this error:

```
08-18 11:08:35.522 18783 18803 W Keychain: You are using a deprecated service which may lead to truncated data on return, please use IOpenPgpService2!
08-18 11:08:35.660 17982 17982 D k9      : OpenPGP Error ID:0
08-18 11:08:35.660 17982 17982 D k9      : OpenPGP Error Message:No encrypted data with known secret key found in stream!
```

I get asked to approve K-9 and select the key, but I'm never prompted for my private key passphrase.

**Comment by dschuermann** [comment] 2016-08-18 16:31
Can you try again with the newest K-9 Mail alpha? There have been many changes in related to PGP. See https://github.com/k9mail/k-9/wiki/AlphaTester

**Comment by jschwartzentruber** [comment] 2016-08-18 16:50
Same error, just displayed differently.
K-9 Mail: 5.110

```
08-18 12:42:52.068   573   573 D k9      : MessageView displaying message MessageReference{accountUuid='4c08592b-f1f4-48a0-b6e8-9eb9e513aabe', folderName='INBOX', uid='1690', flag=null}
08-18 12:42:52.069   573   573 D k9      : Creating new local message loader
08-18 12:42:52.356   573   573 D k9      : OpenPGP API decryptVerify result code: 0
08-18 12:42:52.356   573   573 W k9      : OpenPGP API error: No encrypted data with known secret key found in stream!
08-18 12:42:52.358   573   573 D k9      : Creating new decode message loader
```

**Comment by Valodim** [comment] 2016-08-18 17:11
No idea what this could be, taking the scattershot approach: Is your key "weird" in any way, i.e. did you bind the subkeys in a special way or something like that? When you go to your key, then advanced -> subkeys, are all subkeys listed as expected? In particular, does the encryption key have an encryption icon, and is any subkey marked as stripped/expired/revoked?

**Comment by jschwartzentruber** [comment] 2016-08-18 17:20
No, everything looks normal.
![screenshot_20160818-131755](https://cloud.githubusercontent.com/assets/4673461/17783524/6d24993c-6546-11e6-8cde-d581d273ed91.png)

**Comment by Valodim** [comment] 2016-08-19 09:11
Hm. Indeed, nothing out of the ordinary.. is this only reproducible with email? What client do you use to send the email?

**Comment by jschwartzentruber** [comment] 2016-08-19 15:27
The sender is [Bugzilla](https://github.com/bugzilla/extensions-SecureMail) which uses Perl / Crypt::OpenPGP.

I ran some experiments:
- Encrypt/decrypt local file with OpenKeychain
 - works
- Save encrypted draft from enigmail:
 - K9 doesn't decrypt it, shows an encrypted.asc attachment which I can't detach to try decrypting. (guessing this problem lies in K9)
- Send mail to self w/ PGP/MIME
 - works
- Send mail to self w/ PGP (HTML, Enigmail warns about compatibility)
 - K9 doesn't appear to even try decrypting (guessing this is a K9 problem)
 - gpg2 decrypts only with --ignore-crc-error
```
gpg: armor header: Charset: utf-8
gpg: armor header: Version: GnuPG v2
gpg: CRC error; A38702 - DC3A38
gpg: public key is 836D23A8
gpg: using subkey 836D23A8 instead of primary key 1AF05416
gpg: using subkey 836D23A8 instead of primary key 1AF05416
gpg: encrypted with 8192-bit RSA key, ID 836D23A8, created 2016-04-27
      "Jesse Schwartzentruber <snip>"
gpg: AES256 encrypted data
gpg: original file name=''
```
(another instance of HTML)
```
gpg: armor header: Charset: utf-8
gpg: armor header: Version: GnuPG v2
gpg: malformed CRC
gpg: public key is 836D23A8
gpg: using subkey 836D23A8 instead of primary key 1AF05416
gpg: using subkey 836D23A8 instead of primary key 1AF05416
gpg: encrypted with 8192-bit RSA key, ID 836D23A8, created 2016-04-27
      "Jesse Schwartzentruber <snip>"
gpg: AES256 encrypted data
gpg: original file name=''
```
- Send mail to self w/ PGP (plain-text)
 - works
- Decrypt Bugzilla mail with gpg2:
 - only with --ignore-crc-error
```
gpg: armor header: Comment: https://bugzilla.mozilla.org/show_bug.cgi?id=3Dsnip
gpg: CRC error; 7422DD - DC3742
gpg: public key is 1AF05416
gpg: encrypted with 8192-bit RSA key, ID 1AF05416, created 2016-04-27
      "Jesse Schwartzentruber <snip>"
gpg: CAST5 encrypted data
gpg: original file name=''
```

So I think the issue here is not ignoring CRC errors which it seems enigmail does and OpenKeychain does not. I'm not sure why there are CRC errors.

**Comment by jschwartzentruber** [comment] 2016-08-19 15:33
Forgot to mention, in the above cases I was trying enigmail -> K9. Sending from K9 -> enigmail works.

**Comment by Valodim** [comment] 2016-08-19 20:39
Can you send an email to me in the way you did there which failed? ( -> look@my.amazin.horse )

**Comment by cqcumber** [comment] 2016-08-23 10:00
Hi, I get the same error message when I'm just encrypting and decrypting files.
Here is what I did: 
≡ → Encrypt/Decrypt → Encrypt files → To: (my email-address) → [add a input file] → floppy → (choose an output file name) → (first row 2 images)
≡ → Encrypt/Decrypt → Dencrypt: Select input file → [select the output file] → (second row 2 images)
≡ → Keys → (my key) → ⋮ → Advanced → SUBKEYS → (rightmost image)
![openkeychain_error](https://cloud.githubusercontent.com/assets/3410079/17887520/2dfa7576-6927-11e6-8b24-59bb8e5099b8.png)
Due to this, apps using OpenKeychain don't work either. In my case [Password Store](https://github.com/zeapo/Android-Password-Store). I added to a [bug report](https://github.com/zeapo/Android-Password-Store/issues/173) on their github page first, but it seems that my problem there is based on this issue.
(I'm on Version 4.1 (41010) from Play Store)
If you need me to give you more data to get a better understanding of this issue, please ask. Thanks!

**Comment by dschuermann** [comment] 2016-08-23 10:48
@cqcumber your encryption subkey is not on your device that's why it is shown as "Stripper".

**Comment by dschuermann** [comment] 2016-08-23 10:50
Maybe we should grey out the stripped subkeys like we do it with revoked ones to indicate that they are not usable.

**Comment by cqcumber** [comment] 2016-08-23 11:56
Thank you very much! What a bad mistake I made there (still wondering how that happened). Until today I had the app language not in english but german and the translation of stripped was like shortened. So I missed that while googling. Is it possible for other apps to ask openkeychain via api if the privat key is available? If so I will suggest at Password Store github to implement that query before encrypting/decrypting and raise a propper exception.

**Comment by Valodim** [comment] 2016-08-25 07:52
The better fix here would be #1450, and also we could improve the log messages. "No encrypted data with known secret key" may be technically correct, but we do have more info than that.

**Comment by dschuermann** [comment] 2016-08-26 08:12
It's not a better fix, we should do both and also change the log message.

**Comment by jschwartzentruber** [comment] 2016-09-06 21:26
@Valodim did my email reproduce this for you?

**Comment by pushcx** [comment] 2016-09-13 21:34
@gschwaer It sounds like your problem has been fixed. How did you export and import so the subkey wasn't stripped? I'm having this same problem and no combination of `--export-secret-key` or `--export-secret-subkey` and key name or id will import. The log always says "Keyring contains no new data, nothing to do" and the two subkeys are always listed as stripped.

**Comment by a000a** [comment] 2016-09-15 22:26
Hello!
I'm not sure if it's the same problem, so I don't open a new thread.

Since I'm using in addition to Conversations mcabber the messages sent to me in Conversations are not decryptable anymore.
Openkeychain says 'No valid key found', then I can checkbox my keys and save, but nothing changes.
When I copy the message and try to encrypt it from the the Clipboard, I get 'No data to decrypt!'.
Just when I create a textfile and decrypt it. It works fine.
Also I have no problems to decrypt mails form K9mail.

Conversations 1.14.1
OpenKeychain 4.1
are used.

Thanks for any advice.

**Comment by gschwaer** [comment] 2016-09-16 12:23
@pushcx Sadly it's not in my .bash_history anymore, but reading the man page I think I used something like `gpg2 --armor --export-secret-keys > sec.key` to export the key. For the import I first deleted the existing key from openkeychain (without upload) and then I imported the correct one. Hope this helps.

**Comment by dotnetooo** [comment] 2016-10-31 15:46
I am having the same problem when decrypt  file.'No encrypted data with known secret key found in stream".Any suggestion? Thanks

**Comment by dschuermann** [comment] 2016-12-06 09:53
I renamed this bug report as it is originally about CRC error handling. For other bugs please open a new issue.

**Comment by dschuermann** [comment] 2017-02-08 20:08
This should be fixed with the newest OpenKeychain and K-9 Mail.

**Closed by dschuermann** 2017-02-08 20:08 UTC
